import { chromium } from 'file:///C:/Users/sdd32/Documents/GitHub/Iteration-CFD/gui/node_modules/playwright-core/index.mjs'
const sleep = (ms) => new Promise((r) => setTimeout(r, ms))
const send = async (o) => { await fetch('http://127.0.0.1:8794/send', { method: 'POST', body: JSON.stringify(o) }) }
const seen = async () => (await fetch('http://127.0.0.1:8794/seen')).json()
const browser = await chromium.launch({ headless: true, args: ['--use-angle=swiftshader'] })
const page = await browser.newPage({ viewport: { width: 1600, height: 950 } })
const errs = []
page.on('pageerror', (e) => errs.push(e.message))
await page.goto('http://localhost:5195')
await page.getByTestId('status-connection').waitFor({ timeout: 30000 })
await sleep(1200)
// quick action
await page.locator('.right-quick', { hasText: 'Mesh' }).click()
await sleep(500)
let s = await seen()
console.log('quick:', JSON.stringify(s.quick))
// New chat
await page.getByRole('button', { name: 'New chat' }).click()
await sleep(500)
console.log('messages after new chat:', (await page.getByTestId('assistant-message').allTextContents()).length)
// a turn with thinking + diff + notice + streaming tool input
const sid = 's1'
await send({ t: 'turn.start', sessionId: sid, turnId: 't2', messageId: 'm2' })
await send({ t: 'msg.block_start', sessionId: sid, messageId: 'm2', blockIndex: 0, kind: 'thinking' })
await send({ t: 'msg.delta', sessionId: sid, messageId: 'm2', blockIndex: 0, delta: 'weighing the mesh options' })
await send({ t: 'msg.block_start', sessionId: sid, messageId: 'm2', blockIndex: 1, kind: 'text' })
await send({ t: 'msg.delta', sessionId: sid, messageId: 'm2', blockIndex: 1, delta: 'Editing the case.' })
await send({ t: 'tool.start', sessionId: sid, messageId: 'm2', blockIndex: 2, toolUseId: 'tu9', name: 'case_edit' })
await send({ t: 'tool.input_delta', sessionId: sid, toolUseId: 'tu9', partialJson: '{"path":"cases/plume.jsonc"' })
await sleep(200)
console.log('card while input still streaming:', await page.getByTestId('tool-card').first().textContent().catch(() => '-'))
await send({ t: 'tool.input_delta', sessionId: sid, toolUseId: 'tu9', partialJson: '}' })
await send({ t: 'tool.update', sessionId: sid, call: { toolUseId: 'tu9', name: 'case_edit', input: { path: 'cases/plume.jsonc' }, policy: 'ask', status: 'running', summary: '', resultPreview: null, error: null, runId: null, startedAt: Date.now(), endedAt: null } })
await sleep(600)
console.log('thinking chevron:', await page.locator('.right-think-head').count())
console.log('turn pulse + cancel:', await page.locator('.right-cancel').count())
await page.locator('.right-cancel').click()
await sleep(400)
let s2 = await seen()
console.log('composer after cancel enabled:', await page.getByTestId('composer-input').isEnabled())
await send({ t: 'msg.done', sessionId: sid, message: { id: 'm2', role: 'assistant', blocks: [ { kind: 'text', text: 'Applied the edit.' }, { kind: 'diff', path: 'cases/plume.jsonc', before: 'nu: 1e-5', after: 'nu: 2e-5', applied: true, toolUseId: 'tu9' }, { kind: 'notice', level: 'warning', text: 'the case was changed on disk' } ], createdAt: Date.now(), stopReason: 'end_turn', model: 'fake', suggestions: [], synthetic: false } })
await sleep(600)
console.log('diff block:', await page.locator('.right-diff').count(), 'applied badge:', await page.locator('.right-diff-applied').count())
console.log('notice block:', await page.locator('.right-notice').count(), await page.locator('.right-notice').first().textContent().catch(() => '-'))
console.log('page errors:', JSON.stringify(errs.slice(0, 5)))
await browser.close()
