#!/usr/bin/env python3
# meteor-cfd - Copyright (c) 2026 주식회사 이터레이션즈 (Iterations Co., Ltd.)
# Source-available, not Open Source. See LICENSE at the repository root.
# No GPL-licensed source was consulted.
"""
lreplay.py - recorded tuning rows re-meshed at their recorded config, byte-compared.

The sample is every row of an R-PLANE geometry plus 60 rows stratified by family
and stratum, all with a recorded content sha; each config is rebuilt from the
bundle's own records and deltas and checked against the row's config sha; the
surface is regenerated by campaign.observe and checked against the row's stl
sha; the mesh is compared by score.content_sha256; a changed row is
`changed_fired` only when the layers report carries `n_reseated_points` > 0,
else `changed_unfired`, which fails the run.

The seal holds (a bundle that is not a tuning campaign is refused); the test
split is spent and is not read.

    python tools/autonomy/lreplay.py --plan [--list] [--bundle FILE]
    python tools/autonomy/lreplay.py --run --work DIR --out FILE [--binary EXE] [--streams N] [--ids GID:A,...] [--limit N] [--expect-equal]
    python tools/autonomy/lreplay.py --selftest
"""
import argparse
import collections
import copy
import gzip
import hashlib
import json
import math
import os
import shutil
import subprocess
import sys
import tempfile
import time
import zlib
from concurrent.futures import ThreadPoolExecutor

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
for _p in (HERE, os.path.join(HERE, "corpus")):
    if _p not in sys.path:
        sys.path.insert(0, _p)

import baseline
import campaign
import optimise
import schema
import score
import split

LREPLAY_SCHEMA = "autonomy-lreplay/1"
HEADER = baseline.HEADER
BUNDLE_DEFAULT = os.path.join(HERE, "prior", "tuning_rules.json.gz")
BUNDLE_SCHEMA = "autonomy-baseline-bundle/1"
N_OTHER = 60
SAMPLE_SALT = "lreplay/1"
VERDICTS = ("equal", "changed_fired", "changed_unfired", "surface_mismatch",
            "harness_error")
FAILING = ("changed_unfired", "surface_mismatch", "harness_error")
FIRED_KEYS = ("n_reseated_points",)
STREAMS_DEFAULT = 4
MAX_STREAMS = campaign.MAX_STREAMS


class LReplayError(ValueError):
    """A bundle, a sample or a run that is not what lreplay replays; never guessed past."""


def check_bundle(bundle, name):
    """The seal, then optimise's tuning-only refusal, then the baseline system."""
    if not isinstance(bundle, dict) or bundle.get("schema") != BUNDLE_SCHEMA:
        raise LReplayError("bundle: %s is not a %s bundle" % (name, BUNDLE_SCHEMA))
    optimise.check_bundle(bundle, name)
    system = bundle["campaign"]["system"]
    if system in campaign.BASELINES:
        raise LReplayError("system: %s is a %s baseline; lreplay rebuilds configs "
                           "from the rules' records" % (name, system))


def load_bundle(path):
    """A tuning bundle read through the seal, or a named refusal."""
    if not os.path.isfile(path):
        raise LReplayError("no such bundle file: %s" % path)
    with open(path, "rb") as f:
        data = f.read()
    try:
        b = json.loads(gzip.decompress(data).decode("utf-8"))
    except (OSError, EOFError, ValueError, zlib.error) as e:
        raise LReplayError("bundle: %s does not decompress: %s" % (path, e))
    check_bundle(b, os.path.basename(path))
    return b


def _file_sha256(path):
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()


def rebuild_configs(bundle):
    """{(geometry_id, attempt): config} for every attempt row, from the bundle's
    own attempt-1 rule records and per-row config deltas - never rules.setup."""
    edits1 = {}
    for ln in bundle["records"]:
        rec = ln.get("record") or {}
        if ln.get("attempt") == 1 and rec.get("layer") == "rule":
            edits1.setdefault(ln["geometry_id"], []).extend(rec["edits"])
    by_geom = collections.OrderedDict()
    for r in bundle["attempts"]:
        by_geom.setdefault(r["geometry_id"], {})[r["attempt"]] = r
    out = {}
    for gid in sorted(by_geom):
        att = by_geom[gid]
        if sorted(att) != list(range(1, max(att) + 1)):
            raise LReplayError("attempts: %s holds %s, not 1..%d"
                               % (gid, sorted(att), max(att)))
        base = {"input": {"surfaces": [{"path": campaign.stl_rel(gid)}]},
                "output": {"case_dir": campaign.case_rel(gid), "name": gid}}
        cfg1 = optimise.apply_edits(base, edits1.get(gid, []))
        prev = None
        for a in sorted(att):
            row = att[a]
            parent = cfg1 if a == 1 else prev
            cfg = optimise.apply_edits(parent, row["config_delta"])
            got = schema.canonical_sha256(cfg)
            if got != row["config_sha"]:
                raise LReplayError("rebuild: %s attempt %d rebuilds to %s, the "
                                   "row says %s"
                                   % (gid, a, got[:12], row["config_sha"][:12]))
            prev = cfg
            out[(gid, a)] = cfg
    return out


def plane_geometries(bundle):
    """Gids whose attempt-1 rule record is an applied, non-empty R-PLANE edit."""
    out = set()
    for ln in bundle["records"]:
        rec = ln.get("record") or {}
        if (ln.get("attempt") == 1 and rec.get("rule_id") == "R-PLANE"
                and rec.get("verdict") == "apply" and rec.get("edits")):
            out.add(ln["geometry_id"])
    return out


def sample(bundle, n_other=N_OTHER):
    """The replay sample: every candidate R-PLANE row plus n_other rows drawn
    evenly over the (family, stratum) strata, picked by the sample salt."""
    ends = {g["geometry_id"]: g for g in bundle["geometries"]}
    cands = [r for r in bundle["attempts"]
             if r.get("content_sha256") is not None]
    planes = plane_geometries(bundle)
    plane_rows = [r for r in cands if r["geometry_id"] in planes]
    other = [r for r in cands if r["geometry_id"] not in planes]
    strata = {}
    for r in other:
        gid = r["geometry_id"]
        strata.setdefault((ends[gid]["family"], ends[gid]["stratum"]), []).append(r)
    keys = sorted(strata)
    S = len(keys)
    N = len(other)
    rest = n_other - S
    if rest < 0:
        raise LReplayError("sample: %d other rows over %d strata cannot give a "
                           "quota of one each within %d" % (N, S, n_other))
    q = {}
    frac = {}
    for k in keys:
        x = rest * len(strata[k]) / N
        q[k] = 1 + math.floor(x)
        frac[k] = x - math.floor(x)
    left = n_other - sum(q.values())
    for k in sorted(keys, key=lambda k: (-frac[k], k))[:max(left, 0)]:
        q[k] += 1
    for k in keys:
        if q[k] > len(strata[k]):
            raise LReplayError("sample: stratum %s/%s holds %d other rows, the "
                               "quota is %d" % (k[0], k[1], len(strata[k]), q[k]))
    picked = []
    for k in keys:
        rows = sorted(strata[k], key=lambda r: hashlib.sha256(
            ("%s|%s|%d" % (SAMPLE_SALT, r["geometry_id"], r["attempt"]))
            .encode("ascii")).hexdigest())
        picked.extend(rows[:q[k]])
    entries = []
    for r in plane_rows + picked:
        gid = r["geometry_id"]
        entries.append({"geometry_id": gid, "attempt": r["attempt"],
                        "family": ends[gid]["family"],
                        "stratum": ends[gid]["stratum"],
                        "plane": gid in planes,
                        "config_sha256": r["config_sha"],
                        "recorded_content_sha256": r["content_sha256"],
                        "recorded_seconds": r["outcome"]["seconds"]})
    entries.sort(key=lambda e: (e["geometry_id"], e["attempt"]))
    ids_text = "\n".join("%s:%d" % (e["geometry_id"], e["attempt"])
                         for e in entries)
    sha = hashlib.sha256(ids_text.encode("ascii")).hexdigest()
    return {"rows": entries, "n": len(entries), "n_plane": len(plane_rows),
            "n_plane_geometries": len({r["geometry_id"] for r in plane_rows}),
            "n_other": sum(q.values()), "n_other_pool": N,
            "n_candidates": len(cands), "n_rows_total": len(bundle["attempts"]),
            "n_strata": S,
            "quotas": {"%s/%s" % k: q[k] for k in keys}, "sha256": sha}


def plan_line(s):
    return ("lreplay plan: %d rows = %d R-PLANE rows on %d geometries + %d "
            "stratified of %d other rows (%d with a mesh of %d), sample sha256 %s"
            % (s["n"], s["n_plane"], s["n_plane_geometries"], s["n_other"],
               s["n_other_pool"], s["n_candidates"], s["n_rows_total"],
               s["sha256"]))


def fired_count(summary):
    """The sum of every FIRED_KEYS value over every layers patch, 0 without."""
    if not isinstance(summary, dict):
        return 0
    n = 0
    for st in (summary.get("stages") or []):
        if not isinstance(st, dict) or st.get("stage") != "layers":
            continue
        for p in (st.get("patches") or []):
            for key in FIRED_KEYS:
                n += int(p.get(key) or 0)
    return n


def verdict(recorded, replayed, exit_code, fired):
    if exit_code == 0 and replayed is not None and replayed == recorded:
        return "equal"
    if fired > 0:
        return "changed_fired"
    return "changed_unfired"


def report_ok(counts, expect_equal):
    for v in FAILING:
        if counts.get(v, 0) > 0:
            return False
    if expect_equal and counts.get("equal", 0) != sum(counts.values()):
        return False
    return True


def _mesh(c, gid, a, cfg, run_id):
    """The default mesh_fn, copied from campaign.run_attempt: write the config,
    one full run, the content sha, the summary read back, the polyMesh deleted."""
    campaign.write_config(c, gid, a, cfg)
    job = c.launch([c.binary, campaign.config_rel(gid, a), "-tag", "a%d" % a,
                    "-runId", run_id], cwd=c.dir, timeout_s=campaign.TIMEOUT_S,
                   kind="full", gid=gid, attempt=a, tag="a%d" % a)
    case = os.path.join(c.dir, "cases", "%s_a%d" % (gid, a))
    content = score.content_sha256(case) if job["exit_code"] == 0 else None
    spath = os.path.join(case, "%s_a%d_summary.json" % (gid, a))
    summary = None
    if os.path.isfile(spath):
        with open(spath, encoding="utf-8") as f:
            summary = json.load(f)
    shutil.rmtree(os.path.join(case, "constant", "polyMesh"), ignore_errors=True)
    shutil.rmtree(os.path.join(case, "mesh"), ignore_errors=True)
    return {"exit_code": job["exit_code"], "timed_out": job["timed_out"],
            "seconds": job["seconds"], "content_sha256": content,
            "summary": summary}


def _result(entry, v, replay, exit_code, timed_out, seconds, fired, stl_ok,
            fp_equal, reason):
    r = dict(entry)
    r.update({"verdict": v, "replay_content_sha256": replay,
              "exit_code": exit_code, "timed_out": timed_out, "seconds": seconds,
              "fired": fired, "stl_sha256_ok": stl_ok, "fp_equal": fp_equal,
              "reason": reason})
    return r


def _log_row(log, entry, res):
    if log:
        log("[lreplay] %s a%d %s %s replay %s recorded %s %.1f s"
            % (entry["geometry_id"], entry["attempt"],
               "plane" if entry["plane"] else "other", res["verdict"],
               (res["replay_content_sha256"] or "none")[:12],
               entry["recorded_content_sha256"][:12], res["seconds"] or 0.0))


def _task_rows(c, rows, cfgs, mrows, run_id, ends, observe_fn, mesh_fn, log):
    """One geometry: the surface regenerated and checked, then each attempt
    re-meshed and byte-compared; a fault fails its rows, never passes them."""
    gid = rows[0]["geometry_id"]
    judged = []
    try:
        obs = observe_fn(c, mrows[gid])
        if obs["terminal"] is not None:
            reason = "observe: %s: %s" % (obs["terminal"], obs.get("reason"))
            for e in rows:
                res = _result(e, "harness_error", None, None, None, None, None,
                              None, None, reason)
                judged.append(res)
                _log_row(log, e, res)
            return judged
        stl_sha = _file_sha256(os.path.join(c.dir, "stl", gid + ".stl"))
        want = ends[gid]["fingerprint"]["stl_sha256"]
        stl_ok = stl_sha == want
        fp_equal = (schema.canonical_sha256(obs["fingerprint"])
                    == schema.canonical_sha256(ends[gid]["fingerprint"]))
        if not stl_ok:
            reason = "stl sha %s, the row's surface is %s" % (stl_sha[:12],
                                                              want[:12])
            for e in rows:
                res = _result(e, "surface_mismatch", None, None, None, None,
                              None, False, fp_equal, reason)
                judged.append(res)
                _log_row(log, e, res)
            return judged
        for e in rows:
            m = mesh_fn(c, gid, e["attempt"], cfgs[(gid, e["attempt"])], run_id)
            fired = fired_count(m.get("summary"))
            v = verdict(e["recorded_content_sha256"], m.get("content_sha256"),
                        m.get("exit_code"), fired)
            res = _result(e, v, m.get("content_sha256"), m.get("exit_code"),
                          m.get("timed_out"), m.get("seconds"), fired, True,
                          fp_equal, None)
            judged.append(res)
            _log_row(log, e, res)
        return judged
    except Exception as e:  # noqa: BLE001 - a failing verdict, never a pass
        done = {(r["geometry_id"], r["attempt"]) for r in judged}
        reason = "%s: %s" % (type(e).__name__, e)
        for e2 in rows:
            if (e2["geometry_id"], e2["attempt"]) not in done:
                judged.append(_result(e2, "harness_error", None, None, None,
                                      None, None, None, None, reason))
        return judged


def run_rows(entries, bundle, cfgs, mrows, *, work, binary, streams,
             observe_fn=None, mesh_fn=None, log=None):
    """Every entry re-meshed through the campaign harness, one task per
    geometry, the results sorted by (geometry_id, attempt)."""
    os.makedirs(work, exist_ok=True)
    c = campaign.Campaign(work, campaign_id="lreplay", mode="rules",
                          system="rules", ablate=(),
                          split_mode=bundle["campaign"]["split_mode"],
                          binary=binary, streams=streams,
                          timeout_s=campaign.TIMEOUT_S,
                          probe_timeout_s=campaign.PROBE_TIMEOUT_S,
                          audit_mod=campaign.AUDIT_MOD, quiet=True)
    observe_fn = observe_fn or campaign.observe
    mesh_fn = mesh_fn or _mesh
    run_id = bundle["campaign"]["campaign_id"]
    ends = {g["geometry_id"]: g for g in bundle["geometries"]}
    by_gid = collections.OrderedDict()
    for e in entries:
        by_gid.setdefault(e["geometry_id"], []).append(e)
    for gid in by_gid:
        by_gid[gid].sort(key=lambda e: e["attempt"])
    out = []
    with ThreadPoolExecutor(max_workers=streams) as ex:
        futures = [ex.submit(_task_rows, c, rows, cfgs, mrows, run_id, ends,
                             observe_fn, mesh_fn, log)
                   for rows in by_gid.values()]
        for f in futures:
            out.extend(f.result())
    out.sort(key=lambda r: (r["geometry_id"], r["attempt"]))
    return out


def run(bundle_path, *, work, out, binary, streams=STREAMS_DEFAULT, ids=None,
        limit=None, expect_equal=False, log=print, observe_fn=None, mesh_fn=None):
    """The replay: refuse, load, rebuild, sample, select, run, report."""
    if not isinstance(streams, int) or not 1 <= streams <= MAX_STREAMS:
        raise LReplayError("streams: %r outside 1..%d (the house cap)"
                           % (streams, MAX_STREAMS))
    if not os.path.isfile(binary):
        raise LReplayError("no such binary: %s" % binary)
    if os.path.exists(work) and os.listdir(work):
        raise LReplayError("work: %s is not empty" % work)
    bundle = load_bundle(bundle_path)
    cfgs = rebuild_configs(bundle)
    s = sample(bundle)
    entries = s["rows"]
    if ids is not None:
        by_id = {"%s:%d" % (e["geometry_id"], e["attempt"]): e for e in entries}
        picked = []
        for gid_a in ids:
            e = by_id.get(gid_a)
            if e is None:
                raise LReplayError("id %s is not in the sample" % gid_a)
            picked.append(e)
        entries = picked
    if limit is not None:
        entries = entries[:limit]
    mrows = {r["geometry_id"]: r for r in campaign.load_manifest(
        "tuning", bundle["campaign"]["split_mode"],
        ids=sorted({e["geometry_id"] for e in entries}))}
    t0 = time.perf_counter()
    results = run_rows(entries, bundle, cfgs, mrows, work=work, binary=binary,
                       streams=streams, observe_fn=observe_fn, mesh_fn=mesh_fn,
                       log=log)
    counts = {v: sum(1 for r in results if r["verdict"] == v) for v in VERDICTS}
    ok = report_ok(counts, expect_equal)
    binary_sha = _file_sha256(binary)
    report = {"$comment": HEADER, "schema": LREPLAY_SCHEMA,
              "bundle": {"file": os.path.relpath(bundle_path, REPO)
                         .replace(os.sep, "/"),
                         "sha256": _file_sha256(bundle_path),
                         "campaign_id": bundle["campaign"]["campaign_id"],
                         "recorded_binary_sha256":
                             sorted({r["binary_sha"] for r in bundle["attempts"]})},
              "binary": {"file": os.path.basename(binary),
                         "sha256": binary_sha},
              "sample": {k: v for k, v in s.items() if k != "rows"},
              "selected": {"ids": ids is not None, "limit": limit,
                           "n": len(entries)},
              "expect_equal": expect_equal, "streams": streams,
              "rows": results, "counts": counts, "ok": ok,
              "wall_seconds": time.perf_counter() - t0}
    write_report(report, out)
    n_plane = sum(1 for r in results if r["plane"])
    log("lreplay: %d rows (%d R-PLANE), equal %d, changed_fired %d, "
        "changed_unfired %d, surface_mismatch %d, harness_error %d, "
        "binary %s -> %s"
        % (len(results), n_plane, counts["equal"], counts["changed_fired"],
           counts["changed_unfired"], counts["surface_mismatch"],
           counts["harness_error"], binary_sha[:12], "PASS" if ok else "FAIL"))
    return report


def write_report(report, path):
    d = os.path.dirname(path)
    if d:
        os.makedirs(d, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(report, f, indent=1, sort_keys=True, ensure_ascii=False)
        f.write("\n")


class _ArgParser(argparse.ArgumentParser):
    """Usage errors exit 2, like campaign.py's."""

    def error(self, message):
        self.print_usage(sys.stderr)
        sys.stderr.write("lreplay: error: %s\n" % message)
        raise SystemExit(2)


def main(argv=None):
    ap = _ArgParser(description="recorded tuning rows re-meshed at their "
                                "recorded config, byte-compared")
    ap.add_argument("--selftest", action="store_true")
    ap.add_argument("--plan", action="store_true")
    ap.add_argument("--list", action="store_true", help="with --plan: the ids")
    ap.add_argument("--bundle", metavar="FILE", default=BUNDLE_DEFAULT)
    ap.add_argument("--run", action="store_true")
    ap.add_argument("--work", metavar="DIR")
    ap.add_argument("--out", metavar="FILE")
    ap.add_argument("--binary", metavar="EXE", default=campaign.BINARY_DEFAULT)
    ap.add_argument("--streams", type=int, default=STREAMS_DEFAULT)
    ap.add_argument("--ids", metavar="GID:A,...")
    ap.add_argument("--limit", type=int)
    ap.add_argument("--expect-equal", action="store_true")
    a = ap.parse_args(argv)
    chosen = [k for k, v in (("--selftest", a.selftest), ("--plan", a.plan),
                             ("--run", a.run)) if v]
    if len(chosen) != 1:
        ap.error("exactly one of --selftest, --plan, --run (got %s)"
                 % (", ".join(chosen) or "none"))
    if a.selftest:
        return selftest()
    if a.plan:
        s = sample(load_bundle(a.bundle))
        print(plan_line(s))
        if a.list:
            for e in s["rows"]:
                print("%s:%d %s %s/%s" % (e["geometry_id"], e["attempt"],
                                          "plane" if e["plane"] else "other",
                                          e["family"], e["stratum"]))
        return 0
    if not a.work or not a.out:
        ap.error("--run needs --work DIR and --out FILE")
    ids = None
    if a.ids is not None:
        ids = []
        for item in a.ids.split(","):
            gid, sep, num = item.partition(":")
            if not sep or not num:
                ap.error("--ids: %r is not GID:A" % item)
            try:
                ids.append("%s:%d" % (gid, int(num)))
            except ValueError:
                ap.error("--ids: %r is not GID:A" % item)
    try:
        rep = run(a.bundle, work=a.work, out=a.out, binary=a.binary,
                  streams=a.streams, ids=ids, limit=a.limit,
                  expect_equal=a.expect_equal)
    except (LReplayError, split.SplitSealed) as e:
        sys.stderr.write("lreplay: error: %s\n" % e)
        return 2
    return 0 if rep["ok"] else 1


# --- the selftest ------------------------------------------------------------


def _g1_sample(H):
    b = H["bundle"]
    s = sample(b)
    assert s["n"] == 97, s["n"]
    assert s["n_plane"] == 37, s["n_plane"]
    assert s["n_plane_geometries"] == 36, s["n_plane_geometries"]
    assert s["n_other"] == 60, s["n_other"]
    assert s["n_other_pool"] == 765, s["n_other_pool"]
    assert s["n_candidates"] == 802, s["n_candidates"]
    assert s["n_rows_total"] == 805, s["n_rows_total"]
    assert s["n_strata"] == 16, s["n_strata"]
    assert s["quotas"] == {"A/easy": 1, "A/hard": 6, "A/medium": 6, "B/easy": 2,
                           "B/hard": 8, "B/medium": 6, "D/hard": 2, "D/medium": 9,
                           "E/easy": 3, "E/hard": 2, "E/medium": 2, "F/easy": 1,
                           "F/hard": 3, "F/medium": 2, "G/easy": 5, "G/medium": 2}, \
        s["quotas"]
    assert s["sha256"] == \
        "91b21b3df602594cbc51b61d6a933adee94b8210083720e7616f52f001bee20b", \
        s["sha256"]
    ids = ["%s:%d" % (e["geometry_id"], e["attempt"]) for e in s["rows"]]
    assert ids[:3] == ["A-1-003:1", "A-1-006:1", "A-1-007:2"], ids[:3]
    assert ids[-2:] == ["G-1-106:1", "G-1-117:2"], ids[-2:]
    for e in s["rows"]:
        assert e["recorded_content_sha256"] is not None, e
    plane_rows = [e for e in s["rows"] if e["plane"]]
    pg = plane_geometries(b)
    assert len(plane_rows) == 37, len(plane_rows)
    assert all(e["geometry_id"] in pg for e in plane_rows)
    s2 = sample(b)
    assert s2["rows"] == s["rows"]
    b3 = copy.deepcopy(b)
    for ln in b3["records"]:
        rec = ln.get("record") or {}
        if (ln.get("attempt") == 1 and rec.get("rule_id") == "R-PLANE"
                and rec.get("verdict") == "apply" and rec.get("edits")
                and ln["geometry_id"] == "D-1-042"):
            rec["verdict"] = "pass"
            break
    s3 = sample(b3)
    assert s3["n_plane"] == 36, s3["n_plane"]
    assert s3["n_plane_geometries"] == 35, s3["n_plane_geometries"]
    assert s3["sha256"] != s["sha256"]
    return ("sample: 97 rows = 37 R-PLANE rows on 36 geometries + 60 stratified "
            "of 765 other rows in 16 strata, sample sha256 91b21b3d, "
            "deterministic; the R-PLANE predicate reads the record")


def _g2_rebuild(H):
    b = H["bundle"]
    cfgs = rebuild_configs(b)
    assert len(cfgs) == 805, len(cfgs)
    for r in b["attempts"]:
        got = schema.canonical_sha256(cfgs[(r["geometry_id"], r["attempt"])])
        assert got == r["config_sha"], (r["geometry_id"], r["attempt"])
    import rules
    old = rules.setup

    def _no_setup(*_a, **_k):
        raise AssertionError("rules.setup called")

    rules.setup = _no_setup
    try:
        cfgs2 = rebuild_configs(b)
    finally:
        rules.setup = old
    assert len(cfgs2) == 805, len(cfgs2)
    b3 = copy.deepcopy(b)
    for r in b3["attempts"]:
        if r.get("config_delta"):
            r["config_delta"][0]["to"] = "lreplay-selftest"
            break
    try:
        rebuild_configs(b3)
    except LReplayError as e:
        assert "rebuilds to" in str(e), str(e)
    else:
        raise AssertionError("a changed delta was not refused")
    b4 = copy.deepcopy(b)
    for ln in b4["records"]:
        rec = ln.get("record") or {}
        if ln.get("attempt") == 1 and rec.get("layer") == "rule" \
                and rec.get("edits"):
            rec["edits"] = []
            break
    try:
        rebuild_configs(b4)
    except LReplayError as e:
        assert "rebuilds to" in str(e), str(e)
    else:
        raise AssertionError("a dropped rule edit was not refused")
    b5 = copy.deepcopy(b)
    for r in list(b5["attempts"]):
        gid = r["geometry_id"]
        has3 = any(x["geometry_id"] == gid and x["attempt"] == 3
                   for x in b5["attempts"])
        if r["attempt"] == 2 and has3:
            b5["attempts"].remove(r)
            break
    try:
        rebuild_configs(b5)
    except LReplayError as e:
        assert "not 1.." in str(e), str(e)
    else:
        raise AssertionError("a gap in the attempts was not refused")
    return ("rebuild: 805 configs rebuilt from the bundle's own records and "
            "deltas, each equal to its row's config sha, without rules.setup; "
            "a changed delta, a dropped rule edit and a gap in the attempts "
            "are each refused")


def _g3_seal(H):
    b = H["bundle"]
    b2 = copy.deepcopy(b)
    b2["campaign"]["manifest"]["source"] = "test"
    try:
        check_bundle(b2, "x")
    except split.SplitSealed:
        pass
    else:
        raise AssertionError("a test manifest was not refused")
    b3 = copy.deepcopy(b)
    b3["campaign"]["split_mode"] = split.EVALUATE
    try:
        check_bundle(b3, "x")
    except split.SplitSealed:
        pass
    else:
        raise AssertionError("an evaluate split mode was not refused")
    b4 = copy.deepcopy(b)
    b4["attempts"][0]["split"] = "test"
    try:
        check_bundle(b4, "x")
    except split.SplitSealed:
        pass
    else:
        raise AssertionError("a test row was not refused")
    b5 = copy.deepcopy(b)
    b5["campaign"]["system"] = "b0-template"
    try:
        check_bundle(b5, "x")
    except LReplayError as e:
        assert "baseline" in str(e), str(e)
    else:
        raise AssertionError("a baseline system was not refused")
    b6 = copy.deepcopy(b)
    b6["schema"] = "x"
    try:
        check_bundle(b6, "x")
    except LReplayError as e:
        assert "is not a" in str(e), str(e)
    else:
        raise AssertionError("a wrong schema was not refused")
    with tempfile.TemporaryDirectory() as tmp:
        with open(BUNDLE_DEFAULT, "rb") as f:
            data = bytearray(f.read())
        data[len(data) // 2] ^= 0xFF
        corrupt = os.path.join(tmp, "corrupt.json.gz")
        with open(corrupt, "wb") as f:
            f.write(bytes(data))
        try:
            load_bundle(corrupt)
        except LReplayError as e:
            assert "does not decompress" in str(e), str(e)
        else:
            raise AssertionError("a corrupt bundle was not refused")
        try:
            load_bundle(os.path.join(tmp, "missing.json.gz"))
        except LReplayError as e:
            assert "no such bundle file" in str(e), str(e)
        else:
            raise AssertionError("a missing bundle was not named")
        w = os.path.join(tmp, "wseal")
        try:
            run(BUNDLE_DEFAULT, work=w, out=os.path.join(tmp, "r.json"),
                binary=sys.executable, streams=7)
        except LReplayError as e:
            assert "house cap" in str(e), str(e)
        else:
            raise AssertionError("7 streams were not refused")
        assert not os.path.exists(w)
    return ("seal: a test manifest, an evaluate split mode, a test row and a "
            "baseline system are each refused before anything runs; a corrupt "
            "and a missing bundle are named; 7 streams are refused")


def _g4_verdict(H):
    assert fired_count(None) == 0
    s1 = {"stages": [{"stage": "layers",
                      "patches": [{"n_reseated_points": 3},
                                  {"n_reseated_points": 0}, {}]}]}
    assert fired_count(s1) == 3
    assert fired_count({"stages": [{"stage": "layers", "patches": [{}]}]}) == 0
    assert fired_count({"stages": [
        {"stage": "snap", "patches": [{"n_reseated_points": 5}]}]}) == 0
    a, b = "a" * 64, "b" * 64
    assert verdict(a, a, 0, 0) == "equal"
    assert verdict(a, b, 0, 5) == "changed_fired"
    assert verdict(a, b, 0, 0) == "changed_unfired"
    assert verdict(a, None, 1, 0) == "changed_unfired"
    assert verdict(a, a, 1, 0) == "changed_unfired"
    assert report_ok({"equal": 3}, False)
    assert report_ok({"equal": 3}, True)
    assert report_ok({"equal": 2, "changed_fired": 1}, False)
    assert not report_ok({"equal": 2, "changed_fired": 1}, True)
    for v in FAILING:
        assert not report_ok({"equal": 2, v: 1}, False), v
    return ("verdict: equal, changed_fired and changed_unfired from the content "
            "sha, the exit code and n_reseated_points; ok needs no unfired "
            "change, no surface mismatch and no harness error, and "
            "--expect-equal needs every row equal")


def _g5_scripted(H):
    s = sample(H["bundle"])
    seen = set()
    entries = []
    for e in s["rows"]:
        if e["geometry_id"] not in seen:
            seen.add(e["geometry_id"])
            entries.append(copy.deepcopy(e))
        if len(entries) == 5:
            break
    want = hashlib.sha256(b"solid lreplay-selftest\n").hexdigest()
    b5 = copy.deepcopy(H["bundle"])
    ends = {g["geometry_id"]: g for g in b5["geometries"]}
    for e in entries:
        ends[e["geometry_id"]]["fingerprint"]["stl_sha256"] = want
    gid1, gid2 = entries[0]["geometry_id"], entries[1]["geometry_id"]
    gid3, gid4 = entries[2]["geometry_id"], entries[3]["geometry_id"]
    gid5 = entries[4]["geometry_id"]

    def obs(c, mrow):
        gid = mrow["geometry_id"]
        os.makedirs(os.path.join(c.dir, "stl"), exist_ok=True)
        if gid == gid5:
            return {"terminal": "HARNESS-ERROR", "reason": "scripted"}
        body = b"solid other\n" if gid == gid4 else b"solid lreplay-selftest\n"
        with open(os.path.join(c.dir, "stl", gid + ".stl"), "wb") as f:
            f.write(body)
        return {"terminal": None, "fingerprint": ends[gid]["fingerprint"]}

    def mesh(c, gid, a, cfg, run_id):
        rec = next(e["recorded_content_sha256"] for e in entries
                   if e["geometry_id"] == gid)
        if gid == gid2:
            summary = {"stages": [{"stage": "layers",
                                   "patches": [{"n_reseated_points": 4}]}]}
            body = "0" * 64
        else:
            summary, body = None, (rec if gid == gid1 else "1" * 64)
        return {"exit_code": 0, "timed_out": False, "seconds": 1.0,
                "content_sha256": body, "summary": summary}
    cfgs = rebuild_configs(H["bundle"])
    mrows = {e["geometry_id"]: {"geometry_id": e["geometry_id"]}
             for e in entries}
    with tempfile.TemporaryDirectory() as tmp:
        results = run_rows(entries, b5, cfgs, mrows,
                           work=os.path.join(tmp, "w"), binary=sys.executable,
                           streams=2, observe_fn=obs, mesh_fn=mesh)
        vs = [r["verdict"] for r in results]
        assert vs == ["equal", "changed_fired", "changed_unfired",
                      "surface_mismatch", "harness_error"], vs
        counts = {v: sum(1 for r in results if r["verdict"] == v)
                  for v in VERDICTS}
        assert sorted(counts.values()) == [1] * 5, counts
        assert not report_ok(counts, False), counts
        two = run_rows(entries[:2], b5, cfgs, mrows,
                       work=os.path.join(tmp, "w2"), binary=sys.executable,
                       streams=2, observe_fn=obs, mesh_fn=mesh)
        c2 = {v: sum(1 for r in two if r["verdict"] == v) for v in VERDICTS}
        assert report_ok(c2, False), c2
        assert not report_ok(c2, True), c2
        small = {"$comment": HEADER, "schema": LREPLAY_SCHEMA, "ok": True}
        rp = os.path.join(tmp, "r", "x.json")
        write_report(small, rp)
        with open(rp, encoding="utf-8") as f:
            assert json.load(f) == small
    return ("scripted run: five scripted geometries give equal 1, "
            "changed_fired 1, changed_unfired 1, surface_mismatch 1 and "
            "harness_error 1, and the run is not ok; the report round-trips")


def _g6_live(H):
    with tempfile.TemporaryDirectory() as tmp:
        rep = run(BUNDLE_DEFAULT, work=os.path.join(tmp, "w"),
                  out=os.path.join(tmp, "r.json"),
                  binary=campaign.BINARY_DEFAULT, streams=1,
                  ids=["D-1-042:1"], expect_equal=True, log=lambda s: None)
        assert rep["ok"] is True, rep["counts"]
        assert len(rep["rows"]) == 1, len(rep["rows"])
        row = rep["rows"][0]
        assert row["verdict"] == "equal", row
        assert row["replay_content_sha256"] == \
            "37427fa6910fa9dae93d93cfb742ce7d10fab36d915ba9081a54097346037e61", \
            row["replay_content_sha256"]
        assert row["stl_sha256_ok"] is True, row
        assert row["plane"] is True, row
        with open(os.path.join(tmp, "r.json"), encoding="utf-8") as f:
            disk = json.load(f)
        assert disk["schema"] == LREPLAY_SCHEMA, disk["schema"]
        exe, me = sys.executable, os.path.abspath(__file__)
        p = subprocess.run([exe, me, "--plan"], capture_output=True,
                           encoding="utf-8", errors="replace", timeout=240)
        assert p.returncode == 0, p
        assert p.stdout.splitlines()[0] == plan_line(sample(H["bundle"])), \
            p.stdout.splitlines()[:1]
        p2 = subprocess.run([exe, me, "--run", "--work", os.path.join(tmp, "w2"),
                             "--out", os.path.join(tmp, "r2.json"),
                             "--ids", "Z-9-999:1"], capture_output=True,
                            encoding="utf-8", errors="replace", timeout=240)
        assert p2.returncode == 2, (p2.returncode, p2.stderr[-300:])
        assert "not in the sample" in p2.stderr, p2.stderr[-300:]
        p3 = subprocess.run([exe, me, "--run", "--work", os.path.join(tmp, "w3")],
                            capture_output=True, encoding="utf-8",
                            errors="replace", timeout=240)
        assert p3.returncode == 2, (p3.returncode, p3.stderr[-300:])
    return ("live: D-1-042 attempt 1 (R-PLANE) re-meshed by the release binary "
            "is byte-equal to its recorded content sha 37427fa6; the CLI plans, "
            "and refuses an id outside the sample and a run without --out")


def selftest():
    H = {"bundle": load_bundle(BUNDLE_DEFAULT)}
    groups = (("sample", _g1_sample), ("rebuild", _g2_rebuild),
              ("seal", _g3_seal), ("verdict", _g4_verdict),
              ("scripted run", _g5_scripted), ("live", _g6_live))
    bad = 0
    for name, fn in groups:
        try:
            text = fn(H)
        except Exception as e:  # noqa: BLE001 - the failure IS the report
            bad += 1
            print("SELFTEST FAIL: %s: %s: %s" % (name, type(e).__name__, e))
        else:
            print("[ok] " + text)
    print("SELFTEST PASS" if not bad else "SELFTEST FAIL")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
