#!/usr/bin/env python3
# meteor-cfd - Copyright (c) 2026 주식회사 이터레이션즈 (Iterations Co., Ltd.)
# Source-available, not Open Source. See LICENSE at the repository root.
# No GPL-licensed source was consulted.

"""The Iterations promo opening's stagnation field: write, run, export, inline, check.

The v6 promo opening plays a real planar impinging (stagnation) flow solved by
the pinned GPU solver ``ofgpu-lowmach``: flow enters at x = 0 at 1 m/s, hits a
no-slip wall at x = 3.2 m and turns through two open outlets, on a 56 x 48 x 1
graded channel mesh whose cells tighten toward the wall. ``write`` generates the
mesh with the release ``ofgpu-generate-mesh`` (a separate program), retypes the
preset's patches and writes the laminar case; ``run`` sha256-checks the pinned
binary, records the GPU state before and after and streams the 800-iteration
steady SIMPLE solve into ``solve.log``; ``export`` bilinearly samples the
converged field onto the opening's 64 x 54 grid and writes
``tools/promo/video/opening/stagnation_field.json``; ``inline`` writes that JSON
as one line into title.html between the OPENING-FIELD markers; ``check`` judges
the eight gates G1-G8. Case outputs are never written inside the repository.
numpy (BSD-3) and scipy (BSD-3) are imported. No GPL-licensed source was
consulted.
"""

import argparse
import datetime
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time

import numpy as np
from scipy.interpolate import RegularGridInterpolator

TOOL = "tools/promo/opening_field.py"
REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
GEN = "rust/target/release/ofgpu-generate-mesh.exe"
BIN = "rust/target/gpu-pin/ofgpu-lowmach.exe"
BIN_SHA256 = "50471caaa54125e0c2eee4fb34eebdfc2da44727d2b818a2b96bb4234c02103c"
ITERS = 800
NX, NY = 56, 48
NCELLS = NX * NY
WALL_X = 3.2
EXTENT = [0.0, 3.2, -1.35, 1.35, 0.0, 0.1]
GRADING_X = 0.08
NU = 0.01
U_IN = 1.0
T_IN = 293.15
SAMPLE_X0, SAMPLE_DX, SAMPLE_NX = 0.025, 0.05, 64
SAMPLE_Y0, SAMPLE_DY, SAMPLE_NY = -1.325, 0.05, 54
OUT_JSON = "tools/promo/video/opening/stagnation_field.json"
HTML = "tools/promo/video/compositions/title.html"
MARK_BEGIN = "// OPENING-FIELD-BEGIN (generated by tools/promo/opening_field.py inline - do not edit)"
MARK_END = "// OPENING-FIELD-END"
SCHEMA = "promo-opening-field/1"
# the generator's six block patches, renamed and retyped in boundary-file order
RENAME = [
    ("inlet", "inlet", "patch"),
    ("outlet", "wall", "wall"),
    ("bottomWall", "outletBottom", "patch"),
    ("topWall", "outletTop", "patch"),
    ("back", "back", "empty"),
    ("front", "front", "empty"),
]
DELETE_0 = ["k", "epsilon", "omega", "nut", "nuTilda"]
FOAM_SEP = "// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //"
OFGPU_BANNER = """\
/*---------------------------------------------------------------------------*\\
| ofgpu  --  GPU-native finite volume CFD                                     |
|                                                                             |
| Written in the OpenFOAM ASCII case format so that existing pre- and         |
| post-processing tools can read it. A file format is not a work: ofgpu is    |
| an independent implementation, neither derived from nor affiliated with     |
| OpenFOAM.                                                                   |
\\*---------------------------------------------------------------------------*/"""
LIST_RE = re.compile(r"\n\s*(\d+)\s*\n\s*\(")
NUM_RE = re.compile(r"[-+]?[0-9][0-9.eE+-]*")
ITER_RE = re.compile(
    r"iter\s+(\d+)\s+\|U\|\s+res\s+(\S+)\s+\|p\|\s+res\s+(\S+)")
WALL_RE = re.compile(r"wall_seconds\s+([0-9.]+)")


def fail(code, msg):
    sys.stderr.write("%s: %s\n" % (code, msg))
    sys.exit(2)


def repo_path(rel):
    return os.path.normpath(os.path.join(REPO, rel))


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for blk in iter(lambda: fh.read(1 << 20), b""):
            h.update(blk)
    return h.hexdigest()


def inside_repo(path):
    rp = os.path.realpath(REPO)
    pp = os.path.realpath(os.path.abspath(path))
    return pp == rp or pp.startswith(rp + os.sep)


def list_body(text):
    """The body of the numbered OpenFOAM ASCII list (between its outer parens)."""
    m = LIST_RE.search(text)
    if not m:
        fail("OF-FORMAT", "no numbered ( ... ) list found")
    start = m.end()
    end = text.rindex(")")
    return text[start:end]


def read_points(case):
    text = open(os.path.join(case, "constant", "polyMesh", "points"),
                encoding="utf-8").read()
    vals = np.array(NUM_RE.findall(list_body(text)), dtype=float)
    if vals.size % 3:
        fail("OF-FORMAT", "the points list is not made of triples")
    return vals.reshape(-1, 3)


def read_labels(case, name):
    text = open(os.path.join(case, "constant", "polyMesh", name),
                encoding="utf-8").read()
    return np.array(NUM_RE.findall(list_body(text)), dtype=np.int64)


def read_faces(case):
    text = open(os.path.join(case, "constant", "polyMesh", "faces"),
                encoding="utf-8").read()
    faces = []
    for n, verts in re.findall(r"(\d+)\s*\(([\d\s]*)\)", list_body(text)):
        faces.append(np.array(verts.split(), dtype=np.int64))
        if len(faces[-1]) != int(n):
            fail("OF-FORMAT", "a face's vertex count disagrees with its list")
    return faces


def parse_boundary(text):
    """The boundary file's patch entries as [(name, {key: value}), ...] in order."""
    body = list_body(text)
    out = []
    for name, blk in re.findall(r"([A-Za-z_]\w*)\s*\{([^{}]*)\}", body):
        kv = {}
        for k, v in re.findall(r"([A-Za-z_]\w*)\s+([^;]+);", blk):
            kv[k] = v.strip()
        out.append((name, kv))
    return out


def boundary_text(header, rows):
    lines = [header.rstrip("\n"), "", str(len(rows)), "("]
    for name, typ, nf, sf in rows:
        lines += ["    %s" % name, "    {",
                  "        type            %s;" % typ,
                  "        nFaces          %d;" % nf,
                  "        startFace       %d;" % sf, "    }"]
    lines += [")", "", "// *****************************************************"
              "******************** //", ""]
    return "\n".join(lines)


def foam_dict(obj, location, body_lines):
    parts = [OFGPU_BANNER, "", "FoamFile", "{", "    format      ascii;",
             "    class       dictionary;", '    location    "%s";' % location,
             "    object      %s;" % obj, "}", FOAM_SEP, ""]
    parts += body_lines
    parts += ["", FOAM_SEP, ""]
    return "\n".join(parts)


def foam_field(obj, fclass, dims, internal, patches):
    parts = [OFGPU_BANNER, "", "FoamFile", "{", "    format      ascii;",
             "    class       %s;" % fclass, '    location    "0";',
             "    object      %s;" % obj, "}", FOAM_SEP, "",
             "dimensions      %s;" % dims, "",
             "internalField   %s;" % internal, "", "boundaryField", "{"]
    for name, block in patches:
        parts += ["    %s" % name, "    {"]
        parts += ["        " + ln for ln in block]
        parts.append("    }")
    parts += ["}", "", FOAM_SEP, ""]
    return "\n".join(parts)


def patch_orders():
    return [new for _old, new, _typ in RENAME]


def bc_blocks():
    """0/U, 0/p and 0/T boundary blocks in boundary-file order (C1.3)."""
    blk_u = {
        "inlet": ["type            fixedValue;", "value           uniform (1 0 0);"],
        "wall": ["type            noSlip;"],
        "outletBottom": ["type            zeroGradient;"],
        "outletTop": ["type            zeroGradient;"],
        "back": ["type            empty;"],
        "front": ["type            empty;"],
    }
    blk_p = {
        "inlet": ["type            zeroGradient;"],
        "wall": ["type            zeroGradient;"],
        "outletBottom": ["type            fixedValue;", "value           uniform 0;"],
        "outletTop": ["type            fixedValue;", "value           uniform 0;"],
        "back": ["type            empty;"],
        "front": ["type            empty;"],
    }
    blk_t = {
        "inlet": ["type            fixedValue;", "value           uniform 293.15;"],
        "wall": ["type            zeroGradient;"],
        "outletBottom": ["type            inletOutlet;",
                         "inletValue      uniform 293.15;",
                         "value           uniform 293.15;"],
        "outletTop": ["type            inletOutlet;",
                      "inletValue      uniform 293.15;",
                      "value           uniform 293.15;"],
        "back": ["type            empty;"],
        "front": ["type            empty;"],
    }
    return blk_u, blk_p, blk_t


def write_case(case):
    """C1: generate the graded channel mesh, retype the patches, write the case."""
    case = os.path.abspath(case)
    if inside_repo(case):
        fail("OF-OUT", "--case %s is inside the repository" % case)
    gen = repo_path(GEN)
    if not os.path.isfile(gen):
        fail("OF-NO-BINARY", "the release mesh generator %s is missing" % gen)
    cmd = [gen, "channel", case, str(NX), str(NY), "1",
           "-extent"] + [repr(v) for v in EXTENT] + \
          ["-grading", "x=%s" % GRADING_X, "-grading", "y=1"]
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        sys.stderr.write((proc.stdout or "")[-2000:] + (proc.stderr or "")[-2000:])
        fail("OF-GEN", "the mesh generator exited %d" % proc.returncode)
    # the patches: keep nFaces and startFace, rename and retype (C1.2)
    bpath = os.path.join(case, "constant", "polyMesh", "boundary")
    text = open(bpath, encoding="utf-8").read()
    m = LIST_RE.search(text)
    header = text[:m.start()] if m else ""
    by_name = dict(parse_boundary(text))
    rows = []
    for old, new, typ in RENAME:
        if old not in by_name:
            fail("OF-PATCH", "the preset has no %s patch" % old)
        kv = by_name[old]
        rows.append((new, typ, int(kv["nFaces"]), int(kv["startFace"])))
    with open(bpath, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(boundary_text(header, rows))
    # the three solved fields (C1.3)
    blk_u, blk_p, blk_t = bc_blocks()
    order = patch_orders()
    zero = os.path.join(case, "0")
    with open(os.path.join(zero, "U"), "w", encoding="utf-8", newline="\n") as fh:
        fh.write(foam_field("U", "volVectorField", "[0 1 -1 0 0 0 0]",
                            "uniform (0 0 0)", [(n, blk_u[n]) for n in order]))
    with open(os.path.join(zero, "p"), "w", encoding="utf-8", newline="\n") as fh:
        fh.write(foam_field("p", "volScalarField", "[0 2 -2 0 0 0 0]",
                            "uniform 0", [(n, blk_p[n]) for n in order]))
    with open(os.path.join(zero, "T"), "w", encoding="utf-8", newline="\n") as fh:
        fh.write(foam_field("T", "volScalarField", "[0 0 0 1 0 0 0]",
                            "uniform 293.15", [(n, blk_t[n]) for n in order]))
    for name in DELETE_0:
        p = os.path.join(zero, name)
        if os.path.isfile(p):
            os.remove(p)
    # laminar, and the requested nu (C1.4, C1.5)
    with open(os.path.join(case, "constant", "momentumTransport"), "w",
              encoding="utf-8", newline="\n") as fh:
        fh.write(foam_dict("momentumTransport", "constant",
                           ["simulationType  laminar;"]))
    pppath = os.path.join(case, "constant", "physicalProperties")
    nu_line = "nu              [0 2 -1 0 0 0 0] %s;" % repr(NU)
    if os.path.isfile(pppath):
        ptext = open(pppath, encoding="utf-8").read()
        ptext, n = re.subn(r"nu\s+\[[^\]]*\]\s+[^;]+;", nu_line, ptext, count=1)
        if not n:
            ptext = ptext.replace(FOAM_SEP, FOAM_SEP, 1)
            ptext = re.sub(r"\n(// \*[^/\n]*//\s*)?\Z",
                           "\n\nviscosityModel  constant;\n\n" + nu_line + "\n\n"
                           + FOAM_SEP + "\n", ptext)
    else:
        ptext = foam_dict("physicalProperties", "constant",
                          ["viscosityModel  constant;", "", nu_line])
    with open(pppath, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(ptext)
    print("WRITE OK %s (%d cells, patches %s)"
          % (case, NCELLS, ", ".join(r[0] for r in rows)))
    return case


def nvsmi():
    proc = subprocess.run(
        ["nvidia-smi", "--query-gpu=name,memory.used,utilization.gpu",
         "--format=csv,noheader"], capture_output=True, text=True)
    return " ".join((proc.stdout or "").split())


def run_case(case):
    """C2: write, sha256-check the pinned binary, solve 800 iterations on the GPU."""
    write_case(case)
    binp = repo_path(BIN)
    if not os.path.isfile(binp) or sha256_file(binp) != BIN_SHA256:
        fail("OF-BIN", "%s is missing or its sha256 differs from %s"
             % (binp, BIN_SHA256))
    log = os.path.join(os.path.abspath(case), "solve.log")
    with open(log, "wb") as fh:
        fh.write(("== opening_field run ==\nbinary: %s\nsha256: %s\n"
                  "args: %s -iters %d -check 50\n"
                  % (BIN, BIN_SHA256, os.path.abspath(case), ITERS)).encode())
        fh.write(("nvidia-smi before: %s\n" % nvsmi()).encode())
        fh.flush()
        t0 = time.perf_counter()
        proc = subprocess.run([binp, os.path.abspath(case),
                               "-iters", str(ITERS), "-check", "50"],
                              stdout=fh, stderr=subprocess.STDOUT)
        wall = time.perf_counter() - t0
        fh.write(("\n== run ended exit %d ==\nwall_seconds %.2f\n"
                  "nvidia-smi after: %s\n"
                  % (proc.returncode, wall, nvsmi())).encode())
    if proc.returncode != 0:
        fail("OF-SOLVE", "the solver exited %d; see %s" % (proc.returncode, log))
    print("RUN OK %.2f s wall, log %s" % (wall, log))
    return log


def final_residuals(text):
    """(u_res, p_res, iter_no) from the log's last iter line."""
    last = None
    for m in ITER_RE.finditer(text):
        last = m
    if last is None:
        return None
    return (float(last.group(2)), float(last.group(3)), int(last.group(1)))


def cell_centres(points, faces, owner, neighbour):
    """Each cell centre as the mean of the cell's unique vertices (C3.2)."""
    ncells = int(owner.max()) + 1
    counts = np.array([len(f) for f in faces], dtype=np.int64)
    flat = np.concatenate(faces)
    face_of = np.repeat(np.arange(len(faces), dtype=np.int64), counts)
    cell_of = owner[face_of]
    nint = len(neighbour)
    is_int = face_of < nint
    cells = np.concatenate([cell_of, neighbour[face_of[is_int]]])
    verts = np.concatenate([flat, flat[is_int]])
    pairs = np.unique(np.stack([cells, verts], axis=1), axis=0)
    cnt = np.bincount(pairs[:, 0], minlength=ncells).astype(float)
    cx = np.bincount(pairs[:, 0], weights=points[pairs[:, 1], 0],
                     minlength=ncells) / cnt
    cy = np.bincount(pairs[:, 0], weights=points[pairs[:, 1], 1],
                     minlength=ncells) / cnt
    return cx, cy, ncells


def distinct(vals, tol=1e-9):
    """Group sorted values closer than tol; return (representatives, count)."""
    s = np.sort(np.asarray(vals, dtype=float))
    if not len(s):
        return np.array([]), 0
    groups = np.split(s, np.flatnonzero(np.diff(s) > tol) + 1)
    return np.array([g.mean() for g in groups]), len(groups)


def tensor_grid(cx, cy):
    """Map cell centres onto their (j, i) grid slots; refuse off-grid centres."""
    xr, nx = distinct(cx)
    yr, ny = distinct(cy)
    if nx != NX or ny != NY:
        fail("OF-NOT-STRUCTURED",
             "the centres form a %d x %d grid, not %d x %d" % (nx, ny, NX, NY))
    ix = np.abs(cx[:, None] - xr[None, :]).argmin(axis=1)
    jy = np.abs(cy[:, None] - yr[None, :]).argmin(axis=1)
    if np.abs(cx - xr[ix]).max() > 1e-9 or np.abs(cy - yr[jy]).max() > 1e-9:
        fail("OF-NOT-STRUCTURED", "a cell centre sits off the tensor grid")
    return xr, yr, ix, jy


def read_internal_u(path):
    """The internalField of a volVectorField as an (n, 3) array."""
    text = open(path, encoding="utf-8").read()
    m = re.search(r"internalField\s+uniform\s*\((-?[0-9.eE+-]+)\s+"
                  r"(-?[0-9.eE+-]+)\s+(-?[0-9.eE+-]+)\)\s*;", text)
    if m:
        row = np.array([float(m.group(q)) for q in (1, 2, 3)])
        return np.tile(row, (NCELLS, 1))
    m = re.search(r"internalField\s+nonuniform\s+List<vector>\s*\n?\s*(\d+)\s*\(",
                  text)
    if not m:
        fail("OF-FORMAT", "no readable internalField in %s" % path)
    start = m.end() - 1
    depth = 0
    end = start
    for q in range(start, len(text)):
        if text[q] == "(":
            depth += 1
        elif text[q] == ")":
            depth -= 1
            if depth == 0:
                end = q
                break
    vals = np.array(NUM_RE.findall(text[start + 1:end]), dtype=float)
    if vals.size != int(m.group(1)) * 3:
        fail("OF-FORMAT", "%s holds %d vectors, expected %s"
             % (path, vals.size // 3, m.group(1)))
    return vals.reshape(-1, 3)


def load_case_mesh(case):
    """The mesh's node/centre grids with the centres mapped onto their slots."""
    points = read_points(case)
    faces = read_faces(case)
    owner = read_labels(case, "owner")
    neighbour = read_labels(case, "neighbour")
    cx, cy, ncells = cell_centres(points, faces, owner, neighbour)
    if ncells != NCELLS:
        fail("OF-NOT-STRUCTURED", "the mesh has %d cells, expected %d"
             % (ncells, NCELLS))
    xr_nodes, n_nodes = distinct(points[:, 0])
    xr, yr, ix, jy = tensor_grid(cx, cy)
    return {"node_x": xr_nodes, "n_node_x": n_nodes, "cx": xr, "cy": yr,
            "ix": ix, "jy": jy}


def load_case_field(case):
    """The mesh grids plus the converged cell field mapped by centre (C3.3-4)."""
    fld = load_case_mesh(case)
    vec = read_internal_u(os.path.join(case, str(ITERS), "U"))
    u = np.zeros((NY, NX))
    v = np.zeros((NY, NX))
    u[fld["jy"], fld["ix"]] = vec[:, 0]
    v[fld["jy"], fld["ix"]] = vec[:, 1]
    fld["u"] = u
    fld["v"] = v
    return fld


def build_sampler(cx, cy, u, v):
    """The padded bilinear sampler on the cell-centre tensor grid (C3.6)."""
    xg = np.concatenate([[0.0], np.asarray(cx), [WALL_X]])
    yg = np.concatenate([[EXTENT[2]], np.asarray(cy), [EXTENT[3]]])
    ug = np.concatenate([np.full((len(cy), 1), U_IN), u, np.zeros((len(cy), 1))],
                        axis=1)
    vg = np.concatenate([np.zeros((len(cy), 1)), v, np.zeros((len(cy), 1))],
                        axis=1)
    ug = np.concatenate([ug[:1], ug, ug[-1:]], axis=0)
    vg = np.concatenate([vg[:1], vg, vg[-1:]], axis=0)
    return (RegularGridInterpolator((yg, xg), ug, method="linear"),
            RegularGridInterpolator((yg, xg), vg, method="linear"))


def sample_grid(interp_u, interp_v):
    xs = SAMPLE_X0 + SAMPLE_DX * np.arange(SAMPLE_NX)
    ys = SAMPLE_Y0 + SAMPLE_DY * np.arange(SAMPLE_NY)
    yy, xx = np.meshgrid(ys, xs, indexing="ij")
    pts = np.stack([yy.ravel(), xx.ravel()], axis=1)
    return xs, ys, interp_u(pts).reshape(SAMPLE_NY, SAMPLE_NX), \
        interp_v(pts).reshape(SAMPLE_NY, SAMPLE_NX)


def export_case(case, out):
    """C3: sample the converged field and write the opening's JSON."""
    fld = load_case_field(case)
    interp_u, interp_v = build_sampler(fld["cx"], fld["cy"], fld["u"], fld["v"])
    xs, ys, u, v = sample_grid(interp_u, interp_v)
    mag = np.hypot(u, v)
    log = os.path.join(os.path.abspath(case), "solve.log")
    if not os.path.isfile(log):
        fail("OF-LOG", "no solve.log under %s; run first" % case)
    ltext = open(log, encoding="utf-8", errors="replace").read()
    res = final_residuals(ltext)
    if res is None:
        fail("OF-LOG", "no iter line in %s" % log)
    wm = WALL_RE.search(ltext)
    if wm is None:
        fail("OF-LOG", "no wall_seconds line in %s" % log)
    prov = ("solved by Iterations' own GPU solver ofgpu-lowmach "
            "(sha256 50471caa), steady laminar SIMPLE, %d iterations, planar "
            "impinging flow, inlet 1 m/s at x = 0, no-slip wall at x = 3.2 m, "
            "open outlets at y = -1.35 and 1.35 m, nu 0.01 m2/s, 56 x 48 cells "
            "graded 0.08 toward the wall; final |U| res %.3e, |p| res %.3e; "
            "written by tools/promo/opening_field.py on %s"
            % (ITERS, res[0], res[1], datetime.date.today().isoformat()))
    obj = {
        "schema": SCHEMA,
        "provenance": prov,
        "solver": {"binary": BIN, "sha256": BIN_SHA256, "iters": ITERS,
                   "final_U_res": res[0], "final_p_res": res[1],
                   "wall_s": float(wm.group(1))},
        "case": {"preset": "channel", "cells": [NX, NY, 1], "extent": EXTENT,
                 "grading_x": GRADING_X, "nu": NU, "u_in": U_IN,
                 "model": "laminar"},
        "mesh_x": [round(q, 6) for q in fld["node_x"]],
        "x": [float(q) for q in xs],
        "y": [float(q) for q in ys],
        "u": [[round(float(a), 4) for a in row] for row in u],
        "v": [[round(float(a), 4) for a in row] for row in v],
        "mag": [[round(float(a), 4) for a in row] for row in mag],
    }
    out = os.path.abspath(out)
    parent = os.path.dirname(out)
    if parent:
        os.makedirs(parent, exist_ok=True)
    with open(out, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(obj, fh, ensure_ascii=False, indent=1)
        fh.write("\n")
    print("EXPORT OK %s (%d bytes)" % (out, os.path.getsize(out)))
    return obj


def inline_object(html_text):
    """The object inlined between the OPENING-FIELD markers, or None."""
    m = re.search(r"// OPENING-FIELD-BEGIN[^\n]*\n\s*var OPENING_FIELD = "
                  r"([\s\S]*?);\s*\n\s*// OPENING-FIELD-END", html_text)
    if not m:
        return None
    try:
        return json.loads(m.group(1))
    except ValueError:
        return None


def inline_field(html_path, json_path):
    """Write the JSON object minified as ONE line between the markers."""
    with open(json_path, encoding="utf-8") as fh:
        obj = json.load(fh)
    line = "        var OPENING_FIELD = " + \
        json.dumps(obj, separators=(",", ":"), ensure_ascii=False) + ";"
    with open(html_path, encoding="utf-8") as fh:
        text = fh.read()
    pat = re.compile(r"([ \t]*// OPENING-FIELD-BEGIN[^\n]*\n)"
                     r"[\s\S]*?(\n[ \t]*// OPENING-FIELD-END)")
    new, n = pat.subn(lambda m: m.group(1) + line + m.group(2), text)
    if n != 1:
        fail("OF-HTML", "the OPENING-FIELD markers are missing or not unique "
                        "in %s" % html_path)
    with open(html_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(new)
    print("INLINE OK %s (%d bytes)" % (html_path, len(new.encode("utf-8"))))


def gate_g1(fld):
    node_x = fld["node_x"]
    dx = np.diff(node_x)
    ratio = dx[-1] / dx[0]
    ok = (fld["n_node_x"] == NX + 1 and 0.0799 <= ratio <= 0.0801
          and bool((np.diff(dx) < 0).all()))
    return ok, ("cells %d, %d x-nodes, dx %.6f..%.6f ratio %.6f"
                % (NCELLS, fld["n_node_x"], dx[0], dx[-1], ratio))


def gate_g2(case):
    text = open(os.path.join(case, "constant", "polyMesh", "boundary"),
                encoding="utf-8").read()
    ent = dict(parse_boundary(text))
    want = {"inlet": ("patch", 48), "wall": ("wall", 48),
            "outletBottom": ("patch", 56), "outletTop": ("patch", 56),
            "back": ("empty", NCELLS), "front": ("empty", NCELLS)}
    bad = []
    for name, (typ, nf) in want.items():
        kv = ent.get(name)
        if kv is None or kv.get("type") != typ or int(kv.get("nFaces", -1)) != nf:
            bad.append("%s" % name)
    return not bad, ("six patches ok" if not bad else
                     "wrong: " + ", ".join(bad))


def gate_g34(case):
    log = os.path.join(os.path.abspath(case), "solve.log")
    text = open(log, encoding="utf-8", errors="replace").read()
    res = final_residuals(text)
    if res is None:
        return None
    return res


def gate_g4(fld):
    node_x = fld["node_x"]
    dx = np.diff(node_x)
    out = float((fld["v"][NY - 1] * dx).sum() - (fld["v"][0] * dx).sum())
    rel = abs(out - 2.7) / 2.7
    return rel <= 0.02, "out %.4f (rel %.5f)" % (out, rel)


def gate_g5(u, v):
    du = float(np.abs(u - u[::-1]).max())
    dv = float(np.abs(v + v[::-1]).max())
    return du <= 1e-3 and dv <= 1e-3, \
        "max|u-u'| %.2e, max|v+v'| %.2e" % (du, dv)


def gate_g6(fld):
    u_cl = 0.5 * (fld["u"][23] + fld["u"][24])
    dec = bool((np.diff(u_cl) < 0).all())
    last = float(u_cl[-1])
    mx = float(np.hypot(fld["u"], fld["v"]).max())
    return dec and last <= 0.02 and mx <= 1.2, \
        ("centreline strictly decreasing, last %.6g, max|U| %.5f"
         % (last, mx)) if dec else "centreline not strictly decreasing"


G7_FIXTURES = [
    (27, 32, 1.625, 0.025, 0.7819, 0.0078, 0.7819),
    (27, 60, 3.025, 0.025, 0.0675, 0.0150, 0.0692),
    (40, 63, 3.175, 0.675, 0.0027, 0.1148, 0.1148),
    (45, 50, 2.525, 0.925, 0.4817, 0.5580, 0.7372),
    (0, 40, 2.025, -1.325, 0.8814, -0.5333, 1.0302),
]


def gate_g7(obj):
    keys = ["schema", "provenance", "solver", "case", "mesh_x", "x", "y",
            "u", "v", "mag"]
    if not isinstance(obj, dict) or any(k not in obj for k in keys):
        return False, "missing schema keys"
    if len(obj["u"]) != 54 or len(obj["v"]) != 54 or len(obj["mag"]) != 54:
        return False, "the field is not 54 rows"
    if any(len(r) != 64 for r in obj["u"] + obj["v"] + obj["mag"]):
        return False, "the rows are not 64 wide"
    if len(obj["x"]) != 64 or len(obj["y"]) != 54 or len(obj["mesh_x"]) != 57:
        return False, "the grid arrays have the wrong lengths"
    for j, i, x, y, uu, vv, mm in G7_FIXTURES:
        got = (obj["x"][i], obj["y"][j], obj["u"][j][i], obj["v"][j][i],
               obj["mag"][j][i])
        want = (x, y, uu, vv, mm)
        if any(abs(a - b) > 2e-3 for a, b in zip(got, want)):
            return False, ("fixture (j=%d, i=%d) off: got %s want %s"
                           % (j, i, got, want))
    return True, "5/5 fixtures within 2e-3"


def check_case(case, json_path=None, html_path=None):
    """G1-G8, one [ok]/[FAIL] line each, then CHECK PASS 8/8."""
    case = os.path.abspath(case)
    results = []

    def rec(name, ok, detail):
        results.append(ok)
        print("[%s] %s %s" % ("ok" if ok else "FAIL", name, detail))

    fld = load_case_field(case)
    rec("G1 OF-MESH", *gate_g1(fld))
    rec("G2 OF-PATCH", *gate_g2(case))
    res = gate_g34(case)
    if res is None:
        rec("G3 OF-NOT-CONVERGED", False, "no iter line in solve.log")
    else:
        ok = res[0] <= 1e-6 and res[1] <= 1e-6
        rec("G3 OF-NOT-CONVERGED", ok,
            "|U| %.3e |p| %.3e (iter %d)" % (res[0], res[1], res[2]))
    rec("G4 OF-MASS", *gate_g4(fld))
    rec("G5 OF-SYMMETRY", *gate_g5(fld["u"], fld["v"]))
    rec("G6 OF-STAGNATION", *gate_g6(fld))
    jp = json_path or repo_path(OUT_JSON)
    if not os.path.isfile(jp):
        rec("G7 OF-EXPORT", False, "no %s" % jp)
    else:
        with open(jp, encoding="utf-8") as fh:
            obj = json.load(fh)
        rec("G7 OF-EXPORT", *gate_g7(obj))
    hp = html_path or repo_path(HTML)
    with open(hp, encoding="utf-8") as fh:
        got = inline_object(fh.read())
    if not os.path.isfile(jp):
        rec("G8 OF-INLINE-MISMATCH", False, "no %s to compare" % jp)
    elif got is None:
        rec("G8 OF-INLINE-MISMATCH", False,
            "no parsable object between the markers in %s" % hp)
    else:
        with open(jp, encoding="utf-8") as fh:
            want = json.load(fh)
        rec("G8 OF-INLINE-MISMATCH", got == want,
            "the inlined object %s the JSON file"
            % ("equals" if got == want else "differs from"))
    n_ok = sum(1 for q in results if q)
    print("CHECK %s %d/8" % ("PASS" if n_ok == 8 else "FAIL", n_ok))
    return 0 if n_ok == 8 else 1


def selftest():
    """T1-T6 on the CPU; the generator runs into a temp dir outside the repo."""
    tmp = tempfile.mkdtemp(prefix="opening-field-")
    results = []

    def rec(name, ok, detail=""):
        results.append(ok)
        print("[%s] %s %s" % ("ok" if ok else "FAIL", name, detail))

    try:
        case = os.path.join(tmp, "case")
        write_case(case)
        text = open(os.path.join(case, "constant", "polyMesh", "boundary"),
                    encoding="utf-8").read()
        ent = dict(parse_boundary(text))
        want = {"inlet": ("patch", 48), "wall": ("wall", 48),
                "outletBottom": ("patch", 56), "outletTop": ("patch", 56),
                "back": ("empty", NCELLS), "front": ("empty", NCELLS)}
        ok = (all(name in ent and ent[name].get("type") == typ
                  and int(ent[name].get("nFaces", -1)) == nf
                  for name, (typ, nf) in want.items())
              and not any(os.path.isfile(os.path.join(case, "0", n))
                          for n in ("k", "epsilon", "omega", "nut")))
        rec("T1", ok, "five C1 rows retyped, turbulence fields gone")
        fld = load_case_mesh(case)
        ok = fld["n_node_x"] == 57
        dx = np.diff(fld["node_x"])
        ok = ok and abs(dx[-1] / dx[0] - 0.08) <= 1e-4
        rec("T2", ok, "%d x-nodes, dx ratio %.8f" % (fld["n_node_x"],
                                                     dx[-1] / dx[0]))
        # T3: the padded bilinear sampler reproduces a linear cell field. The
        # inlet/wall pads carry u = 1 and u = 0, which this field's own values
        # at x = 0 and x = 3.2, so u is exact at every sample; the pads' v = 0
        # is the inlet plane's value, not 0.5*y, so v is exact only where the
        # stencil touches true cell columns (and, below, only inside the cell
        # rows, where the y zero-gradient pads are copies).
        u_cell = np.tile(1.0 - fld["cx"] / WALL_X, (NY, 1))
        v_cell = np.tile(0.5 * fld["cy"][:, None], (1, NX))
        iu, iv = build_sampler(fld["cx"], fld["cy"], u_cell, v_cell)
        xs, ys, u_s, v_s = sample_grid(iu, iv)
        err_u = float(np.abs(u_s - (1.0 - xs[None, :] / WALL_X)).max())
        band = (ys >= fld["cy"][0] - 1e-9) & (ys <= fld["cy"][-1] + 1e-9)
        core = band[:, None] \
            & (xs >= fld["cx"][0] - 1e-9)[None, :] \
            & (xs <= fld["cx"][-1] + 1e-9)[None, :]
        err_v = float(np.abs(v_s - 0.5 * ys[:, None])[core].max())
        rec("T3", err_u <= 1e-9 and err_v <= 1e-9,
            "max |du| %.2e all samples, max |dv| %.2e inside the cell rows"
            % (err_u, err_v))
        got = final_residuals("iter    799  |U| res 4.006e-10  "
                              "|p| res 5.919e-09  contErr 1e-11")
        rec("T4", got is not None and abs(got[0] - 4.006e-10) <= 1e-18
            and abs(got[1] - 5.919e-09) <= 1e-18,
            "parsed %r" % (got,))
        obj = {"schema": SCHEMA, "provenance": "t", "solver": {},
               "case": {}, "mesh_x": [0.0, 3.2], "x": [0.025],
               "y": [-1.325], "u": [[1.0]], "v": [[0.5]], "mag": [[1.118]]}
        jpath = os.path.join(tmp, "field.json")
        with open(jpath, "w", encoding="utf-8") as fh:
            json.dump(obj, fh)
        hpath = os.path.join(tmp, "title-copy.html")
        with open(hpath, "w", encoding="utf-8", newline="\n") as fh:
            fh.write("<!doctype html><html><body><script>\n"
                     "        " + MARK_BEGIN + "\n"
                     "        var OPENING_FIELD = {};\n"
                     "        " + MARK_END + "\n"
                     "</script></body></html>\n")
        inline_field(hpath, jpath)
        with open(hpath, encoding="utf-8") as fh:
            good = inline_object(fh.read()) == obj
        with open(hpath, encoding="utf-8") as fh:
            htext = fh.read()
        htext = re.sub(r"-?\d+\.\d+",
                       lambda m: repr(float(m.group(0)) + 1.0), htext, count=1)
        bad = inline_object(htext) != obj
        rec("T5", good and bad, "inline + G8 compare %s, one-number edit %s"
            % ("passes" if good else "FAILS", "fails" if bad else "PASSES"))
        u = np.tile(np.linspace(1.0, 0.0, NX), (NY, 1))
        base = 0.01 * np.sin(np.linspace(0.0, 3.0, NX))[None, :]
        v_bad = np.tile(base, (NY, 1))
        srow = np.where(np.arange(NY) < NY // 2, 1.0, -1.0)[:, None]
        v_good = np.tile(base, (NY, 1)) * srow
        ok_bad = not gate_g5(u, v_bad)[0]
        ok_good = gate_g5(u, v_good)[0]
        rec("T6", ok_bad and ok_good,
            "v(j)=v(47-j) fails G5, v(j)=-v(47-j) passes")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)
    n_ok = sum(1 for q in results if q)
    print("SELFTEST %s %d/6" % ("PASS" if n_ok == 6 else "FAIL", n_ok))
    return 0 if n_ok == 6 else 1


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--selftest", action="store_true",
                    help="run T1-T6 on the CPU and exit")
    sub = ap.add_subparsers(dest="cmd")
    w = sub.add_parser("write", help="write the case (CPU only)")
    w.add_argument("--case", required=True)
    r = sub.add_parser("run", help="write + the pinned GPU solve")
    r.add_argument("--case", required=True)
    ex = sub.add_parser("export", help="write the opening's field JSON")
    ex.add_argument("--case", required=True)
    ex.add_argument("--out", default=None)
    inl = sub.add_parser("inline", help="inline the JSON into title.html")
    inl.add_argument("--html", default=None)
    inl.add_argument("--json", default=None)
    ck = sub.add_parser("check", help="judge G1-G8")
    ck.add_argument("--case", required=True)
    ck.add_argument("--json", default=None)
    ck.add_argument("--html", default=None)
    args = ap.parse_args()
    if args.selftest:
        sys.exit(selftest())
    if args.cmd == "write":
        write_case(args.case)
    elif args.cmd == "run":
        run_case(args.case)
    elif args.cmd == "export":
        export_case(args.case, args.out or repo_path(OUT_JSON))
    elif args.cmd == "inline":
        inline_field(args.html or repo_path(HTML),
                     args.json or repo_path(OUT_JSON))
    elif args.cmd == "check":
        sys.exit(check_case(args.case, args.json, args.html))
    else:
        ap.print_help()
        sys.exit(2)


if __name__ == "__main__":
    main()
