// gui/shared/src/ontology/seed/dc.equations.ts — the twenty Equation rows of
// the data-centre seed. An Equation is seeded only if something else in the
// seed points at it; the deferred ids, with their reasons, are in dc.types.ts.
// Every symbol table is transcribed verbatim from the fact sheet and is
// human-checked territory (docs/13 section 3): add nothing, drop nothing.
import { dcRow, sym, type SeedObject } from './dc.types.js'

const E = (id: string, name: string, latex: string,
           symbols: Array<{ symbol: string; unit: string; meaning: string }>,
           validity: string, specSection: string | null, citation: string,
           verification: string, sourcePath: string): SeedObject =>
  dcRow('Equation', id, sourcePath, {
    id, name, latex, symbols, validity, specSection, citation, verification,
  })

export const DC_EQUATIONS: readonly SeedObject[] = Object.freeze([
  E('EQ-C4', 'Buoyancy body force, density ratio', 'b = g (T_{ref}/T - 1)',
    [sym('b', 'm/s2', 'body acceleration'), sym('g', 'm/s2', 'gravity vector'),
     sym('T', 'K', 'local absolute temperature'), sym('T_ref', 'K', 'buoyancy reference temperature')],
    'Exact in the body force for an ideal gas at constant pressure; `b` is exactly zero at `T = T_ref`. Not Boussinesq: no expansion coefficient and no small-temperature-difference assumption',
    'S9', 'This project\'s own specification, section 9; implemented at `rust/src/momentum.rs`', 'VERIFIED', 'rust/src/momentum.rs'),
  E('EQ-B7', 'Virtual temperature', 'T_v = T (1 + (1/\\epsilon - 1) Y_v)',
    [sym('T_v', 'K', 'virtual temperature'), sym('T', 'K', 'dry-bulb absolute temperature'),
     sym('Y_v', 'kg/kg', 'vapour mass fraction'), sym('\\epsilon', 'dimensionless', 'ratio of molar masses, 0.621945')],
    'Exact, not a linearisation. The coefficient is 0.607858. At 25 C a move from 20 to 80 per cent relative humidity shifts `T_v` by about 2.1 K, which is a sixth of a typical rack temperature rise',
    'S54.7', 'This project\'s own specification, section 54.4; `\\epsilon` from Gatley, Herrmann & Kretzschmar, HVAC&R Research 14(5) (2008) 655-662, DOI 10.1080/10789669.2008.10391032', 'VERIFIED', 'rust/src/psychro.rs'),
  E('EQ-C6', 'Species transport, one inert scalar', '\\partial_t Y + \\nabla\\cdot(\\phi Y) - \\nabla\\cdot(D_{eff} \\nabla Y) = S',
    [sym('Y', 'kg/kg', 'transported mass fraction'), sym('\\phi', 'm3/s', 'face volume flux'),
     sym('D_eff', 'm2/s', 'effective diffusivity'), sym('Sc_t', 'dimensionless', 'turbulent Schmidt number'),
     sym('S', '1/s', 'source')],
    '0 <= Y <= 1 is enforced. Costs one extra sparse solve per outer iteration. The data-centre driver builds exactly one such scalar, the vapour fraction',
    'S19', 'This project\'s own specification, section 19; humidity as one species, section 54.1', 'VERIFIED', 'rust/src/scalar_transport.rs'),
  E('EQ-P6', 'Dew-point temperature', 't_d = 6.54 + 14.526 a + 0.7389 a^2 + 0.09486 a^3 + 0.4569 p_w^{0.1984}',
    [sym('t_d', 'degrees Celsius', 'dew-point temperature'), sym('a', 'dimensionless', 'natural logarithm of `p_w`'),
     sym('p_w', 'kPa', 'water-vapour partial pressure')],
    'The form above holds from 0 to 93 C; below 0 C the two-term branch `t_d = 6.09 + 12.608 a + 0.4959 a^2` applies. `p_w` is in kilopascals, not pascals — the commonest error in this relation',
    'S54.3', 'ASHRAE Handbook-Fundamentals psychrometrics chapter, equations 37 and 38, as transcribed in this project\'s own specification; implemented at `rust/src/psychro.rs`', 'PARTIAL', 'rust/src/psychro.rs'),
  E('EQ-T1', 'Standard k-epsilon', '\\nu_t = C_\\mu k^2/\\varepsilon',
    [sym('nu_t', 'm2/s', 'turbulent viscosity'), sym('k', 'm2/s2', 'turbulent kinetic energy'),
     sym('varepsilon', 'm2/s3', 'dissipation rate'), sym('C_mu', 'dimensionless', 'coefficient, 0.09')],
    'The workhorse two-equation closure. It over-predicts round-jet spreading and is weak in an adverse pressure gradient; in a buoyant plume it is only as good as the buoyancy production term it is given',
    'S6', 'Launder & Spalding, Computer Methods in Applied Mechanics and Engineering 3 (1974) 269-289', 'VERIFIED', 'rust/SPEC-LIT.md'),
  E('EQ-T9', 'Standard wall function', 'u^+ = \\ln(E y^+)/\\kappa',
    [sym('u+', 'dimensionless', 'wall-parallel velocity'), sym('y+', 'dimensionless', 'wall distance'),
     sym('kappa', 'dimensionless', 'von Karman constant, 0.41'), sym('E', 'dimensionless', 'roughness parameter, 9.8')],
    'Valid for `y+` between about 30 and 300, and it assumes local equilibrium. It is wrong at separation, at reattachment, and on a wall where buoyancy dominates the shear',
    'S6.4', 'This project\'s own specification, section 6.4; the log law of the wall, with the laminar crossover solved by fixed point at set-up rather than hard-coded', 'VERIFIED', 'rust/SPEC-LIT.md'),
  E('EQ-B2', 'Richardson number', 'Ri = g \\beta \\Delta T L / U^2',
    [sym('Ri', 'dimensionless', 'Richardson number'), sym('beta', '1/K', 'expansion coefficient'),
     sym('Delta T', 'K', 'temperature difference'), sym('L', 'm', 'length scale'), sym('U', 'm/s', 'velocity scale')],
    '`Ri` far below one is forced convection, near one is mixed, far above one is stratified. The gradient form exceeding 0.25 means shear cannot overturn the stratification',
    null, 'Miles, Journal of Fluid Mechanics 10 (1961) 496-508; Howard, same volume, 509-512', 'VERIFIED', 'docs/13-data-centre-axis.md'),
  E('EQ-B4', 'Grashof over Reynolds squared', 'Gr/Re^2 = g \\beta \\Delta T L / U^2',
    [sym('Gr', 'dimensionless', 'Grashof number'), sym('Re', 'dimensionless', 'Reynolds number'),
     sym('beta', '1/K', 'expansion coefficient'), sym('Delta T', 'K', 'wall-to-air temperature difference'),
     sym('L', 'm', 'length scale'), sym('U', 'm/s', 'approach velocity')],
    'The test that decides whether a shear wall function is valid at all. Far below one, the log law holds; near one it is suspect and the thermal law worse; far above one the wall is in natural convection and neither holds. A hall at 2 m/s gives about 0.18 and a stalled aisle at 0.2 m/s about 18, so one mesh straddles both',
    null, 'The standard mixed-convection criterion; Incropera & DeWitt, Fundamentals of Heat and Mass Transfer, section 9.9; Jaluria, Natural Convection Heat and Mass Transfer, Pergamon (1980)', 'PARTIAL', 'docs/13-data-centre-axis.md'),
  E('EQ-M1', 'Rack as a heat source over a cell zone', 'S_u = \\dot{Q}/(\\rho c_p V)',
    [sym('S_u', 'K/s', 'explicit temperature source'), sym('Q-dot', 'W', 'stated rack power'),
     sym('rho', 'kg/m3', 'air density'), sym('c_p', 'J/kg/K', 'specific heat'),
     sym('V', 'm3', 'total volume of the rack\'s cells')],
    'The rack heats the air and does not move it: no rack patches, no blockage, no internal resistance. The equipment temperature rise is therefore always derived, never measured',
    'S18', 'This project\'s own specification, section 18; the worked case `cases/coldAisle.dc.jsonc`', 'VERIFIED', 'rust/SPEC-LIT.md'),
  E('EQ-M3', 'Power to airflow', '\\dot{Q}_{IT} = \\rho \\dot{V} c_p \\Delta T_{rack}',
    [sym('Q-dot_IT', 'W', 'total IT power'), sym('rho', 'kg/m3', 'air density'),
     sym('V-dot', 'm3/s', 'volume flow through the rack'), sym('c_p', 'J/kg/K', 'specific heat'),
     sym('Delta T_rack', 'K', 'air temperature rise across the rack')],
    'Steady, all IT power to air, no loss to the slab. At 1.2 kg/m3 and 1005 J/kg/K the coefficient is about 1206, so 8 kW at an 11 K rise is about 0.60 m3/s — which is why the shipped case pairs 8000 W with 0.62 m3/s',
    'S55.2', 'This project\'s own specification, section 55.2; the first law', 'VERIFIED', 'rust/SPEC-LIT.md'),
  E('EQ-M4', 'Fan curve as a boundary condition', 'p_b = p_a - \\sigma F(Q_{dev}), \\quad F(Q) = \\Delta p_{fan}(Q)/\\rho_{ref}',
    [sym('p_b', 'm2/s2', 'kinematic pressure on the far side'), sym('p_a', 'm2/s2', 'kinematic pressure on the near side'),
     sym('sigma', 'dimensionless', 'direction sign, plus one for outflow and minus one for inflow'),
     sym('Q_dev', 'm3/s', 'the device\'s own gathered volume flow'), sym('Delta p_fan', 'Pa', 'manufacturer pressure rise'),
     sym('rho_ref', 'kg/m3', 'reference density')],
    'Pressure is kinematic throughout this solver, which is the commonest unit error when a component model is coupled to it. The quadratic form is written odd, `Q` times the absolute value of `Q`, never `Q` squared: the even form makes the reverse branch a positive-feedback runaway',
    'S52', 'This project\'s own specification, section 52; the external gate is the NIST FDS fan verification case, US public domain; AMCA 210 and ASHRAE 51 are paywalled and were not opened', 'VERIFIED', 'rust/src/fan.rs'),
  E('EQ-M5', 'Fan affinity laws', 'Q_2/Q_1 = N_2/N_1, \\quad \\Delta p_2/\\Delta p_1 = (N_2/N_1)^2 (\\rho_2/\\rho_1), \\quad P_2/P_1 = (N_2/N_1)^3 (\\rho_2/\\rho_1)',
    [sym('Q', 'm3/s', 'volume flow'), sym('N', 'any consistent unit', 'rotational speed'),
     sym('Delta p', 'Pa', 'pressure rise'), sym('rho', 'kg/m3', 'density'), sym('P', 'W', 'shaft power')],
    'Geometric similarity, fixed diameter, Reynolds number high enough that efficiency does not move with speed; fails at deep turndown. The correction is applied at every evaluation, not once: a 40 C return is 6.4 per cent less dense than the 20 C a curve is usually measured at',
    'S52.5', 'Buckingham-pi derivation, Bhattacharjee, arXiv:1211.0676 (open); the ASHRAE Handbook fan chapter is paywalled and was not opened', 'VERIFIED', 'rust/src/fan.rs'),
  E('EQ-M6', 'Fan shaft power', 'W_{fan} = Q \\Delta p_{fan}(Q) / \\eta_{total}',
    [sym('W_fan', 'W', 'shaft power at the converged operating point'), sym('Q', 'm3/s', 'the device\'s volume flow'),
     sym('Delta p_fan', 'Pa', 'pressure rise at that flow'),
     sym('eta_total', 'dimensionless', 'total efficiency, greater than zero and at most one')],
    'Efficiency outside that interval is refused by name. Summed over fans, this is one of the three numbers a facility model can honestly take from a room model',
    'S55.5', 'This project\'s own specification, sections 55.4 and 55.5; implemented at `rust/src/fan.rs`', 'VERIFIED', 'rust/src/fan.rs'),
  E('EQ-M7', 'Porous jump, a resistive face', '\\Delta p_{kin} = -R(\\lvert\\phi_f\\rvert)\\, \\phi_f, \\quad R = (r_{visc} + r_{inert} \\lvert\\phi_f\\rvert / a_f)/a_f',
    [sym('Delta p_kin', 'm2/s2', 'kinematic pressure jump'), sym('phi_f', 'm3/s', 'face volume flux'),
     sym('a_f', 'm2', 'face area'),
     sym('r_visc', '1/s', 'viscous resistance, kinematic viscosity times thickness over permeability'),
     sym('r_inert', '1/m', 'inertial resistance, half the inertial coefficient times thickness')],
    '`R` is never negative, which is what makes the condition unconditionally stable with no sign branch. Scalars stay continuous across it — a jump is not a baffle. The tile form is the special case with `r_visc` zero and `r_inert` equal to half the loss coefficient',
    'S53', 'This project\'s own specification, section 53; implemented at `rust/src/fan.rs`', 'VERIFIED', 'rust/src/fan.rs'),
  E('EQ-M8', 'Tile loss coefficient from open-area ratio', 'K(\\sigma) = [0.707 (1-\\sigma)^{0.375} + (1-\\sigma)]^2 / \\sigma^2',
    [sym('K', 'dimensionless', 'loss coefficient on the approach velocity'),
     sym('sigma', 'dimensionless', 'open-area ratio, greater than zero and at most one')],
    'Thin-plate form, referred to the approach velocity. It gives 30.68 at a quarter open, 4.370 at half and 2.937 at 0.56 — the gates are the two limits, `K` to zero as `sigma` approaches one and `K` to infinity as `sigma` approaches zero, and the specification records that a quoted value of about 4 at 0.56 is contradicted by the formula. The derived `K` is always printed',
    'S53.6', 'Idelchik, Handbook of Hydraulic Resistance, 4th ed., Begell (2007) — paywalled; the formula as transcribed in this project\'s own specification', 'PARTIAL', 'rust/src/fan.rs'),
  E('EQ-M11', 'Sensible heat ratio at a coil, with apparatus dew point and bypass factor', 'SHR = \\min[(h(T_{in}, W_{ADP}) - h_{ADP})/(h_{in} - h_{ADP}),\\ 1], \\quad BF = \\exp(-NTU)',
    [sym('SHR', 'dimensionless', 'sensible heat ratio'), sym('h_in', 'kJ per kg dry air', 'inlet enthalpy'),
     sym('h_ADP', 'kJ per kg dry air', 'enthalpy of saturated air at the apparatus dew point'),
     sym('W_ADP', 'kg/kg', 'humidity ratio at the apparatus dew point'), sym('BF', 'dimensionless', 'bypass factor'),
     sym('NTU', 'dimensionless', 'number of transfer units')],
    'The apparatus-dew-point and bypass-factor pair is the only honest place a latent load is accounted. A ratio of one means a dry coil, which is where a data hall should sit. **Nothing in this solver implements it**: the row exists so the chat can say what a coil model would need',
    null, 'EnergyPlus Engineering Reference, "Coils" (US Department of Energy documentation, public), fetched 2026-09-15', 'VERIFIED', 'docs/13-data-centre-axis.md'),
  E('EQ-D-RCI', 'Rack Cooling Index', 'RCI_{HI} = [1 - \\sum_x \\max(0, T_x - T_{hi,rec}) / ((T_{hi,all} - T_{hi,rec}) n)] \\times 100\\%',
    [sym('RCI_HI', 'per cent', 'high-side rack cooling index'), sym('T_x', 'K', 'one rack-inlet sample temperature'),
     sym('T_hi,rec', 'K', 'the class\'s recommended high limit'), sym('T_hi,all', 'K', 'the class\'s allowable high limit'),
     sym('n', 'dimensionless', 'number of sample points')],
    '100 per cent means no inlet is outside the recommended band at all; zero means every inlet sits at the allowable limit. **The value depends on which sample points are used**, so the sample set is part of the definition and is reported with the number. The low-side form is the mirror, with a recommended-low minus allowable-low denominator. The envelope is stored in Celsius and converted to kelvin before comparison',
    'S55.1', 'Herrlin, "Rack cooling effectiveness in data centers and telecom central offices: the Rack Cooling Index", ASHRAE Transactions 111(2) (2005) 725-731, no DOI — paywalled; the formula as transcribed in this project\'s own specification', 'VERIFIED', 'rust/src/dcmetrics.rs'),
  E('EQ-D-RTI', 'Return Temperature Index', 'RTI = (T_r - T_s)/\\Delta T_{equipment} \\times 100\\%',
    [sym('RTI', 'per cent', 'return temperature index'), sym('T_r', 'K', 'flux-weighted return-air temperature'),
     sym('T_s', 'K', 'flux-weighted supply-air temperature'),
     sym('Delta T_equipment', 'K', 'mean air temperature rise across the IT equipment')],
    'Below 100 per cent is bypass, above is recirculation, 100 is ideal. At steady state with all IT heat leaving through the return it equals the ratio of IT mass flow to supply mass flow, so **halving the supply flow exactly doubles it, whatever the geometry** — a gate that needs no external data. The two temperatures must be flux-weighted patch means, never area means',
    'S55.2', 'Herrlin, "Airflow and cooling performance of data centers: two performance metrics", ASHRAE Transactions 114(2) (2008) 182-187, no DOI — paywalled; the formula as printed in the LBNL self-benchmarking guide', 'VERIFIED', 'rust/src/dcmetrics.rs'),
  E('EQ-D-SHI', 'Supply and Return Heat Index', 'SHI = \\delta Q/(Q + \\delta Q), \\quad RHI = 1 - SHI',
    [sym('SHI', 'dimensionless', 'supply heat index'), sym('RHI', 'dimensionless', 'return heat index'),
     sym('delta Q', 'W', 'pre-heat picked up by the cold air before it reaches the racks'),
     sym('Q', 'W', 'useful heat pickup at the racks')],
    '`SHI` approaching zero is ideal. The implementation forms the denominator once and subtracts, so the two sum to exactly one in floating point — a property of the implementation, gated as such. Here `Q` is the stated rack power, not a measured mass flow times a measured rise, so the pair holds only under the heat-zone modelling assumption',
    'S55.3', 'Sharma, Bash & Patel, "Dimensionless parameters for evaluation of thermal design and performance of large-scale data centers", AIAA 2002-3091, DOI 10.2514/6.2002-3091 — paywalled; the form as carried in this project\'s own specification', 'PARTIAL', 'rust/src/dcmetrics.rs'),
  E('EQ-D-PUE', 'The three inputs a room model can offer towards a facility ratio', '\\{W_{fan},\\ \\dot{Q}_{IT},\\ \\max T_s\\ \\text{with}\\ RCI_{HI} = 100\\%\\}',
    [sym('W_fan', 'W', 'total fan shaft power at the converged operating points'),
     sym('Q-dot_IT', 'W', 'total IT heat from the cell-zone releases'),
     sym('max T_s', 'K', 'the highest supply temperature at which the high-side index stays at 100 per cent')],
    '**This is not a PUE and no PUE is computed from it.** The third input is the free-cooling ceiling, and it is absent on every run today because the supply-temperature sweep that would find it is parsed and never read',
    'S55.4', 'This project\'s own specification, section 55.4; implemented at `rust/src/dcmetrics.rs`', 'VERIFIED', 'rust/src/dcmetrics.rs'),
])
