// gui/shared/src/ontology/seed/dc.standards.ts — the thirty-one Standard rows
// and eighteen StandardClause rows of the data-centre seed, plus the two
// edition links. A clause is a locator, our own one-line claim, and a
// publicValue only when a public source states it and that source is named by
// id: the words of a standard never enter this file (docs/13, sections 4-5).
import { clauseId, dcRow, dcLink, type SeedLink, type SeedObject } from './dc.types.js'

const SRC = 'docs/13-data-centre-axis.md' // section 5 is this repository's own corpus statement

const S = (id: string, issuer: string, number: string, edition: string, title: string,
           licence: string, isPaywalled: boolean, accessNote: string): SeedObject =>
  dcRow('Standard', id, SRC, { standardId: id, issuer, number, edition, title, licence, isPaywalled, accessNote })

export const DC_STANDARDS: readonly SeedObject[] = Object.freeze([
  S('ASHRAE:TC9.9:5', 'ASHRAE', 'TC9.9', '5',
    'Thermal Guidelines for Data Processing Environments, 5th ed. (2021)',
    'ASHRAE copyright, no redistribution',
    true, 'purchase from the ASHRAE bookstore, ISBN 978-1-947192-90-4'),
  S('ASHRAE:TC9.9:2011-whitepaper', 'ASHRAE', 'TC9.9', '2011-whitepaper',
    '2011 Thermal Guidelines — Expanded Data Center Classes and Usage Guidance',
    '(c) 2011 ASHRAE; the notice forbids reproduction and posting',
    true, 'a third-party mirror exists and was not fetched; cross-check only'),
  S('ASHRAE:90.4:2022', 'ASHRAE', '90.4', '2022',
    'Energy Standard for Data Centers',
    'ASHRAE copyright',
    true, 'purchase; the free fact sheet and Addendum h are the public sources'),
  S('ASHRAE:90.4:2019-addendum-h', 'ASHRAE', '90.4', '2019-addendum-h',
    'Addendum h to Standard 90.4-2019, ANSI-approved 2022-11-08',
    '(c) 2022 ASHRAE, ISSN 1041-2336; reproduction not permitted',
    false, 'free from ashrae.org; structure described, tables not reproduced'),
  S('ASHRAE:Journal:2022-05', 'ASHRAE', 'Journal', '2022-05',
    'ASHRAE\'s Data Center Thermal Guidelines — Air-Cooled Evolution, May 2022',
    '(c) 2022 ASHRAE, posted publicly',
    false, 'free; numeric values reported, text not copied'),
  S('ISO/IEC:30134-2:2', 'ISO/IEC', '30134-2', '2',
    'Information technology — Data centres — Key performance indicators — Part 2: Power usage effectiveness, ed. 2.0, 2026-01-16',
    'ISO/IEC copyright',
    true, 'purchase, CHF 159, IEC publication 111538, 35 pp.'),
  S('ISO/IEC:30134-2:1', 'ISO/IEC', '30134-2', '1',
    'the 2016 first edition, superseded',
    'ISO/IEC copyright',
    true, 'superseded; purchase'),
  S('CENELEC:FprEN-50600-4-2:2016', 'CENELEC', 'FprEN 50600-4-2', '2016',
    'Power Usage Effectiveness, final draft for vote',
    'CENELEC copyright',
    false, 'a public draft circulated for national-committee vote; the formula is cited as a formula'),
  S('CENELEC:EN-50600-4-2:2016', 'CENELEC', 'EN 50600-4-2', '2016',
    'Power Usage Effectiveness',
    'CENELEC copyright',
    true, 'purchase from a national body'),
  S('CENELEC:EN-50600-4-3:2019', 'CENELEC', 'EN 50600-4-3', '2019',
    'Renewable Energy Factor',
    'CENELEC copyright', true, 'purchase'),
  S('CENELEC:EN-50600-4-6:2020', 'CENELEC', 'EN 50600-4-6', '2020',
    'Energy Reuse Factor',
    'CENELEC copyright',
    true, 'purchase; the public preview had no extractable text'),
  S('CENELEC:EN-50600-4-7:2020', 'CENELEC', 'EN 50600-4-7', '2020',
    'Cooling Efficiency Ratio',
    'CENELEC copyright', true, 'purchase'),
  S('CENELEC:EN-50600-4-9:2022', 'CENELEC', 'EN 50600-4-9', '2022',
    'Water Usage Effectiveness',
    'CENELEC copyright', true, 'purchase'),
  S('CENELEC:EN-50600-2-3:2019', 'CENELEC', 'EN 50600-2-3', '2019',
    'Environmental control',
    'CENELEC copyright',
    true, 'purchase; only a cover-and-contents preview is public, so no numeric environmental requirement may be coded from it'),
  S('JRC:CoC:2024', 'JRC', 'CoC', '2024',
    '2024 Best Practice Guidelines for the EU Code of Conduct on Data Centre Energy Efficiency, JRC136986',
    'CC BY 4.0 under Commission Decision 2011/833/EU', false, 'free'),
  S('JRC:CoC:2025', 'JRC', 'CoC', '2025',
    'the 2025 edition, JRC141521, DOI 10.2760/9449356',
    'CC BY 4.0', false, 'free'),
  S('EU:2023/1791:2023', 'EU', '2023/1791', '2023',
    'Energy Efficiency Directive recast, Article 12 and Annex VII',
    '(c) EU, reuse authorised', false, 'free on EUR-Lex'),
  S('EU:2024/1364:2024', 'EU', '2024/1364', '2024',
    'Commission Delegated Regulation on a common Union rating scheme for data centres',
    '(c) EU, reuse authorised',
    false, 'free on EUR-Lex; the fetch returned an empty body, so read Annexes I and II before coding the indicator list'),
  S('TGG:WP35:1', 'The Green Grid', 'WP35', '1',
    'Water Usage Effectiveness: A Green Grid Data Center Sustainability Metric',
    'The Green Grid copyright', false, 'free download'),
  S('TGG:WP49:1', 'The Green Grid', 'WP49', '1',
    'PUE: A Comprehensive Examination of the Metric',
    'The Green Grid copyright', false, 'free download'),
  S('TGG:WP32:1', 'The Green Grid', 'WP32', '1',
    'Carbon Usage Effectiveness',
    'The Green Grid copyright', false, 'free download'),
  S('LBNL:self-benchmarking:2009', 'LBNL', 'self-benchmarking', '2009',
    'Self-benchmarking Guide for Data Centers: Metrics, Benchmarks, Actions, 13 July 2009',
    'prepared under US Government sponsorship, no restrictive licence', false, 'free from OSTI'),
  S('Herrlin:ASHRAE-Trans-111(2):2005', 'ASHRAE', 'Transactions 111(2)', '2005',
    'Rack cooling effectiveness in data centers and telecom central offices: the Rack Cooling Index, pp. 725-731',
    'ASHRAE copyright', true, 'purchase; no DOI'),
  S('Herrlin:ASHRAE-Trans-114(2):2008', 'ASHRAE', 'Transactions 114(2)', '2008',
    'Airflow and cooling performance of data centers: two performance metrics, pp. 182-187',
    'ASHRAE copyright', true, 'purchase; no DOI'),
  S('Sharma:AIAA-2002-3091:2002', 'AIAA', '2002-3091', '2002',
    'Dimensionless parameters for evaluation of thermal design and performance of large-scale data centers',
    'AIAA copyright', true, 'purchase, DOI 10.2514/6.2002-3091'),
  S('Tozer:ASHRAE-Trans-115(1):2009', 'ASHRAE', 'Transactions 115(1)', '2009',
    'Air management metrics in data centers',
    'ASHRAE copyright', true, 'purchase'),
  S('Shrivastava:ASHRAE-Trans-113(1):2007', 'ASHRAE', 'Transactions 113(1)', '2007',
    'Capture index: an airflow-based rack cooling performance metric, pp. 126-136',
    'ASHRAE copyright', true, 'purchase; the public AIVC record carries the abstract'),
  S('Uptime:Tier-Topology:2013-2026', 'Uptime Institute', 'Tier Standard: Topology', '2013-2026',
    'Tier Standard: Topology',
    '(c) 2013-2026 Uptime Institute, all rights reserved',
    true, 'gated download; certification is a paid service'),
  S('TIA:942-C:2024', 'TIA', '942-C', '2024',
    'Telecommunications Infrastructure Standard for Data Centers, published May 2024',
    'TIA copyright', true, 'purchase; the white paper and brochure are public'),
  S('Wibron:Energies-12(8)1473:2019', 'MDPI', 'Energies 12(8) 1473', '2019',
    'Comparing performance metrics of partial aisle containments in hard floor and raised floor data centers',
    'CC BY 4.0, licence verified via Crossref',
    false, 'full text was not reachable from this environment'),
  S('Kuzay:Data-in-Brief-45:2022', 'Elsevier', 'Data in Brief 45, 108587', '2022',
    'Numerical and experimental dataset for a retrofitted data center',
    'CC BY 4.0', false, 'open access; data at Zenodo DOI 10.5281/zenodo.7035829'),
])

// A clause carries a locator, our own claim about what the clause governs,
// and a publicValue only when a named public source states it. There is no
// text property on the type and none may be invented (docs/13, section 3,
// rule 4). The A2 and JRC 5.3.1 values carry an EN DASH on purpose: that
// string is C5's end-to-end contract, copied character for character from
// docs/13 section 5's worked example, and every other band uses a hyphen.
const C = (standardId: string, locator: string, claim: string,
           publicValue: string | null, publicSource: string | null, verification: string): SeedObject => {
  const id = clauseId(standardId, locator)
  return dcRow('StandardClause', id, SRC, {
    clauseId: id, standardId, locator, claim, publicValue, publicSource, verification,
  })
}

export const DC_CLAUSES: readonly SeedObject[] = Object.freeze([
  C('ASHRAE:TC9.9:5', 'Table 3 / class A1',
    'sets the A1 allowable dry-bulb range at the ITE inlet',
    '15-32 °C', 'doc:ashrae-journal-2022-05', 'VERIFIED'),
  C('ASHRAE:TC9.9:5', 'Table 3 / class A2',
    'sets the A2 allowable dry-bulb range at the ITE inlet',
    '10–35 °C', 'doc:ashrae-journal-2022-05', 'VERIFIED'),
  C('ASHRAE:TC9.9:5', 'Table 3 / class A3',
    'sets the A3 allowable dry-bulb range at the ITE inlet',
    '5-40 °C', 'doc:ashrae-journal-2022-05', 'VERIFIED'),
  C('ASHRAE:TC9.9:5', 'Table 3 / class A4',
    'sets the A4 allowable dry-bulb range at the ITE inlet',
    '5-45 °C', 'doc:ashrae-journal-2022-05', 'VERIFIED'),
  C('ASHRAE:TC9.9:5', 'Table 3 / class H1',
    'sets the H1 allowable dry-bulb range at the ITE inlet, for high-density air-cooled servers',
    '5-25 °C', 'doc:ashrae-journal-2022-05', 'VERIFIED'),
  C('ASHRAE:TC9.9:5', 'Table 2 / recommended dry-bulb',
    'sets one recommended dry-bulb band for classes A1 to A4 and a narrower one for H1',
    '18-27 °C for A1-A4; 18-22 °C for H1', 'doc:ashrae-journal-2022-05', 'VERIFIED'),
  C('ASHRAE:TC9.9:5', 'Table 2 / recommended moisture',
    'sets the upper recommended moisture limit, and makes it depend on measured gaseous corrosion',
    '70 % RH or a 15 °C dew point, whichever is drier; 50 % where corrosion exceeds the coupon thresholds',
    'doc:ashrae-journal-2022-05', 'VERIFIED'),
  C('ASHRAE:TC9.9:2011-whitepaper', 'Table 3 / rate of change',
    'limits how fast the inlet temperature may move, with a tighter limit where tape is used',
    '20 °C/h with disk drives, 5 °C/h with tape drives', 'doc:hvac-best-ashrae-tc99', 'PARTIAL'),
  C('ASHRAE:90.4:2022', 'scope',
    'sets the floor-area power density and IT load above which the standard applies',
    'above 20 W/ft² and above 10 kW of ITE load', 'doc:ashrae-90-4-2022-fact-sheet', 'VERIFIED'),
  C('ASHRAE:90.4:2022', 'Table 6.5',
    'sets the maximum annualised mechanical load component by climate zone and ITE size band',
    null, null, 'UNVERIFIED'),
  C('CENELEC:FprEN-50600-4-2:2016', 'eq. 1',
    'defines the facility energy ratio as total data-centre energy over IT equipment energy, over a coincident twelve-month period',
    'PUE = E_DC / E_IT', 'doc:fpren-50600-4-2-2016', 'VERIFIED'),
  C('CENELEC:FprEN-50600-4-2:2016', '6.2 / categories',
    'makes where the IT load is measured part of the reported metric, as a subscript',
    'category 1 at the UPS output, 2 at the PDU output, 3 at the IT equipment',
    'doc:fpren-50600-4-2-2016', 'VERIFIED'),
  C('JRC:CoC:2024', '5.3.1',
    'asks that intake air at the IT equipment be delivered within the ASHRAE class A2 allowable range, expected value 4',
    '10–35 °C', 'doc:jrc-coc-2024', 'VERIFIED'),
  C('JRC:CoC:2024', '5.1',
    'names computational fluid dynamics as the way to reach an optimal airflow design when it is used before construction or fit-out',
    null, 'doc:jrc-coc-2024', 'VERIFIED'),
  C('LBNL:self-benchmarking:2009', 'metric A3',
    'fixes the sign of the return index: below one hundred per cent is bypass, above it is recirculation',
    'below 100 % is bypass, above 100 % is recirculation', 'doc:lbnl-self-benchmarking-2009', 'VERIFIED'),
  C('LBNL:self-benchmarking:2009', 'metric A4',
    'defines airflow efficiency as total fan power over total fan airflow and names a better-practice figure',
    '0.5 W/cfm is better practice', 'doc:lbnl-self-benchmarking-2009', 'VERIFIED'),
  C('TGG:WP35:1', 'eq. 2',
    'defines water usage effectiveness as annual site water over annual IT equipment energy',
    'WUE = annual site water (L) / IT equipment energy (kWh)', 'doc:tgg-wp35-wue', 'VERIFIED'),
  C('Uptime:Tier-Topology:2013-2026', 'Tier III',
    'makes maintenance on any cooling capacity component or distribution path possible without affecting the IT load, making the one-unit-down case a design case',
    null, null, 'PARTIAL'),
])

export const DC_STANDARD_LINKS: readonly SeedLink[] = Object.freeze([
  dcLink('Standard', 'supersedes', 'ISO/IEC:30134-2:2', 'ISO/IEC:30134-2:1', SRC),
  dcLink('Standard', 'equivalentTo', 'CENELEC:EN-50600-4-2:2016', 'ISO/IEC:30134-2:2', SRC),
])
